# -*- coding: utf-8 -*-
"""ke_kv_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KrRx1g0jAjn9ehSGVy4TWT4dh79-fdEe
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/ke2motors2Flywheels.csv')
pd.set_option('display.min_rows', 15)
print(df.shape) # displays the number of rows and columns of the array
df # prints the actual data

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Assuming data is in data.csv with columns 'time' and 'velocity'
# df = pd.read_csv('data.csv')

# Example data generation for demonstration
data = {
    'time': [1, 2, 3, 5, 6, 7, 10, 11, 12, 13],
    'velocity': [1300, 1280, 940, 1310, 1290, 960, 1320, 1300, 950, 940]
}
df = pd.DataFrame(data)

# 1. Split dataset where time difference > 1
df['time_diff'] = df['time'].diff().fillna(0)
df['session_id'] = (df['time_diff'] > 1).cumsum()

sessions = [group for _, group in df.groupby('session_id')]
print(f'Detected {len(sessions)} independent data segments.')

import pandas as pd
df = pd.read_csv('/content/ke2motors2Flywheels.csv')
x = df['applied_voltage'].values
x= x.reshape(-1, 1)
y = df['velocity'].values

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Plot the original data
plt.plot(x, y, color='blue', label='data')

# Add labels to the axes
plt.xlabel('applied_voltage')
plt.ylabel('velocity')

# Add a legend
plt.legend()

# Display the plot
plt.show()

model = LinearRegression(fit_intercept=False)
model.fit(x, y)
y_pred = model.predict(x)

plt.plot(x, y_pred) # Plot the original data
plt.scatter(x, y, color='blue', label='ke calculator')

# Add labels to the axes
plt.xlabel('applied-voltage')
plt.ylabel('velocity')

# Add a legend
plt.legend()

# Display the plot
plt.show()



"""# Task
Print the intercept and coefficient of the linear regression model.

## Export Linear Function

### Subtask:
Access and print the intercept and coefficient (slope) of the fitted `LinearRegression` model to get the linear function's parameters.

**Reasoning**:
Access and print the intercept and coefficient of the fitted LinearRegression model to fulfill the subtask instructions.
"""

intercept = model.intercept_
coefficient = model.coef_[0]

print(f"Intercept: {intercept}")
print(f"Coefficient (Slope): {coefficient}")

model = LinearRegression(fit_intercept=False)
x = df['velocity'].values.reshape(-1, 1)
y = df['applied_voltage'].values
print(x.shape)
print(y.shape)

model.fit(x, y)
y_pred = model.predict(x)

import matplotlib.pyplot as plt

plt.plot(x, y_pred)# Plot the original data
plt.scatter(x, y, color='blue', label='kv calculator')

# Add labels to the axes
plt.xlabel('velocity')
plt.ylabel('applied voltage')

# Add a legend
plt.legend()

# Save the plot to a file before showing it
plt.savefig('kv_calculator_plot.png')

# Display the plot
plt.show()

# from google.colab import drive
# drive.mount('/content/drive')

# import shutil
# import os

# source_path = 'kv_calculator_plot.png'
# destination_folder = '/content/drive/My Drive/plotImages'

# # Ensure the destination folder exists
# if not os.path.exists(destination_folder):
#     os.makedirs(destination_folder)

# destination_path = os.path.join(destination_folder, os.path.basename(source_path))

# shutil.copyfile(source_path, destination_path)
# print(f"Image '{source_path}' saved to '{destination_path}'")



intercept = model.intercept_
coefficient = model.coef_[0]

print(f"Intercept: {intercept}")
print(f"Coefficient (Slope): {coefficient}")