# -*- coding: utf-8 -*-
"""throughput.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LT70OFUSgeePIRE604WaVW7QDU1OGypT
"""

import pandas as pd
import numpy as np

file = "testThrouputWith2Wheels1.csv"

df = pd.read_csv(f'/content/{file}')
pd.set_option('display.min_rows', 15)
print(df.shape) # displays the number of rows and columns of the array
df # prints the actual data

# Using a Median Filter to ignore 'jumps' and snapping to 20-unit increments
# This removes the 1140-1120-1140 jitter without adding the lag of alpha=0.3

# 1. Apply a small rolling median to remove single-point outliers
df['filtered_velocity'] = df['shooter_velocity'].rolling(window=3, center=True).median().fillna(df['shooter_velocity'])

# 2. 'Smart' snapping: Round to the nearest 20 units to eliminate discretization noise
df['filtered_velocity'] = (df['filtered_velocity'] / 20).round() * 20

print("Applied Median Filter + 20-unit snapping to remove quantization noise.")
display(df[['time', 'shooter_velocity', 'filtered_velocity']].head(10))

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(df['time'], df['shooter_velocity'], label='Original Shooter Velocity', alpha=0.7)
plt.plot(df['time'], df['filtered_velocity'], label=f'Filtered Velocity (alpha={alpha})', color='red')
plt.xlabel('Time')
plt.ylabel('Velocity')
plt.title('Original vs. Smoothed Shooter Velocity')
plt.legend()
plt.grid(True)
plt.show()

x = df['time'].values
x= x.reshape(-1, 1)
y = df['shooter_velocity'].values

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

# Plot the original data
plt.scatter(x, y, color='blue', label='data')

# Add labels to the axes
plt.xlabel('time')
plt.ylabel('velocity')

# Add a legend
plt.legend()

# Display the plot
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Split the dataset based on time difference > 1
df['time_diff'] = df['time'].diff().fillna(0) # Changed 'applied_voltage' to 'time'

# Create a grouping ID based on the time gap
df['group_id'] = (df['time'].diff() > 1).cumsum() # Changed 'applied_voltage' to 'time'

groups = [group for _, group in df.groupby('group_id')]
print(f'Detected {len(groups)} independent data segments.')

import matplotlib.pyplot as plt

plt.figure(figsize=(14, 7))

# Tuning parameters to merge clusters
MIN_DROP_DEPTH = 40
COOLDOWN = 0.3 # Increased from 0.1 to 0.3 to group points from the same ball

for i, segment in enumerate(groups):
    plt.subplot(len(groups), 1, i + 1)

    target = segment['shooter_target'].iloc[0] if 'shooter_target' in segment.columns else 1300

    # 1. Identify all points deep enough to be a drop
    depth_mask = (segment['filtered_velocity'] <= target - MIN_DROP_DEPTH)

    # 2. Identify local minima (points lower than or equal to neighbors)
    condition = (
        depth_mask &
        (segment['filtered_velocity'] <= segment['filtered_velocity'].shift(1).fillna(9999)) &
        (segment['filtered_velocity'] <= segment['filtered_velocity'].shift(-1).fillna(9999))
    )

    potential_points = segment[condition].copy()

    # 3. Apply Cooldown to merge nearby detections into a single event
    final_drops = []
    last_time = -1
    for _, row in potential_points.iterrows():
        if row['time'] > last_time + COOLDOWN:
            final_drops.append(row)
            last_time = row['time']

    significant_drops = pd.DataFrame(final_drops)

    print(f"Segment {i}: {len(significant_drops)} drops detected (using COOLDOWN={COOLDOWN}s).")

    plt.plot(segment['time'], segment['shooter_velocity'], label='Raw Data', color='gray', alpha=0.3)
    plt.plot(segment['time'], segment['filtered_velocity'], label='Snapped Filter', color='blue', linewidth=2, marker='o', markersize=4, alpha=0.8)
    plt.axhline(y=target, color='green', linestyle='--', label=f'Target ({target})', alpha=0.5)

    if not significant_drops.empty:
        plt.scatter(significant_drops['time'], significant_drops['filtered_velocity'],
                    color='red', s=350, marker='X', label='Detected Drop', zorder=20)

    plt.title(f'Segment {i}: Detection Results (3 Drops Expected)')
    plt.xlabel('Time (s)')
    plt.ylabel('Velocity')
    plt.legend(loc='lower left', frameon=True, shadow=True)
    plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

SLOPE_TRIGGER = -500
COOLDOWN = 0.15 # Reduced cooldown to capture events like the one at 37.20s

# Ensure slope is calculated
if 'filtered_velocity' in df.columns:
    df['velocity_slope'] = np.gradient(df['filtered_velocity'], df['time'])

# Find indices where the slope is sharper than our threshold
drops_by_slope = df[df['velocity_slope'] < SLOPE_TRIGGER].copy()

# Apply cooldown logic to group consecutive points into one event
final_slope_events = []
last_time = -1
for _, row in drops_by_slope.iterrows():
    if row['time'] > last_time + COOLDOWN:
        final_slope_events.append(row)
        last_time = row['time']

slope_events_df = pd.DataFrame(final_slope_events)

plt.figure(figsize=(14, 6))
plt.plot(df['time'], df['filtered_velocity'], label='Filtered Velocity', color='blue')
plt.plot(df['time'], df['velocity_slope'], label='Slope (dv/dt)', color='purple', alpha=0.3)

if not slope_events_df.empty:
    plt.scatter(slope_events_df['time'], slope_events_df['filtered_velocity'],
                color='orange', s=200, marker='D', label='Slope Triggered Drop', zorder=25)

plt.axhline(y=SLOPE_TRIGGER, color='red', linestyle='--', label=f'Threshold ({SLOPE_TRIGGER})', alpha=0.5)
plt.title(f'Drop Detection using Velocity Slope Threshold ({SLOPE_TRIGGER})')
plt.xlabel('Time (s)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print(f'Detected {len(slope_events_df)} drops using slope threshold.')
print("Significant Negative Slopes found (including 37.20s region):")
display(df[(df['time'] >= 37.1) & (df['time'] <= 37.3)][['time', 'velocity_slope']])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. Calculate the gradient on RAW velocity to catch the sharpest possible impacts
df['raw_velocity_slope'] = np.gradient(df['shooter_velocity'], df['time'])

# 2. Parameters for universal detection
RAW_SLOPE_TRIGGER = -800  # Sharp enough to be an impact, but loose enough to catch all balls
GROUPING_WINDOW = 0.2     # Seconds: Group rapid sequential spikes into one ball event

# 3. Find all potential impact points
impact_candidates = df[df['raw_velocity_slope'] < RAW_SLOPE_TRIGGER].copy()

# 4. Grouping Logic: Iterate and only pick the first spike of a sequence
confirmed_events = []
if not impact_candidates.empty:
    last_event_time = -1
    for _, row in impact_candidates.iterrows():
        if row['time'] > last_event_time + GROUPING_WINDOW:
            confirmed_events.append(row)
            last_event_time = row['time']

events_df = pd.DataFrame(confirmed_events)

# 5. Full Dataset Visualization
plt.figure(figsize=(15, 7))
plt.plot(df['time'], df['shooter_velocity'], label='Raw Shooter Velocity', color='gray', alpha=0.4)
plt.plot(df['time'], df['filtered_velocity'], label='Smoothed Trend', color='blue', alpha=0.8)

if not events_df.empty:
    plt.scatter(events_df['time'], events_df['shooter_velocity'],
                color='red', s=150, marker='*', label='Detected Ball Impact', zorder=10)

plt.title(f'Universal Ball Detection: {len(events_df)} Events Found (Threshold: {RAW_SLOPE_TRIGGER})')
plt.xlabel('Time (s)')
plt.ylabel('Velocity')
plt.grid(True, which='both', linestyle='--', alpha=0.5)
plt.legend()
plt.show()

print(f"Summary: Identified {len(events_df)} ball events.")
display(events_df[['time', 'shooter_velocity', 'raw_velocity_slope']])

# Calculate slope using the RAW shooter velocity instead of the filtered one
df['raw_velocity_slope'] = np.gradient(df['shooter_velocity'], df['time'])

plt.figure(figsize=(14, 6))
plt.plot(df['time'], df['shooter_velocity'], label='Raw Velocity', color='gray', alpha=0.5)
plt.plot(df['time'], df['raw_velocity_slope'], label='Raw Slope (dv/dt)', color='red', alpha=0.7)

# Highlight where the raw slope exceeds a very sharp threshold
RAW_SLOPE_TRIGGER = -1000
sharp_spikes = df[df['raw_velocity_slope'] < RAW_SLOPE_TRIGGER]

if not sharp_spikes.empty:
    plt.scatter(sharp_spikes['time'], sharp_spikes['shooter_velocity'],
                color='black', s=100, label=f'Spikes < {RAW_SLOPE_TRIGGER}')

plt.axhline(y=RAW_SLOPE_TRIGGER, color='black', linestyle='--', label='Raw Slope Threshold')
plt.title('Slope Analysis using RAW Sensor Data')
plt.xlabel('Time (s)')
plt.ylabel('Velocity / Slope')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

print("Top 5 Sharpest RAW Slopes:")
display(df.sort_values('raw_velocity_slope').head(5)[['time', 'shooter_velocity', 'raw_velocity_slope']])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Define the threshold for what we consider a 'drop' using the raw slope
RAW_SLOPE_TRIGGER = -1000
EVENT_COOLDOWN = 0.1  # seconds: any spikes within this window count as 1 ball

# 1. Find all points where the raw slope is sharp enough
raw_spikes = df[df['raw_velocity_slope'] < RAW_SLOPE_TRIGGER].copy()

# 2. Group sequential drops into a single event
final_events = []
if not raw_spikes.empty:
    last_time = -1
    for _, row in raw_spikes.iterrows():
        # If this spike happens after the cooldown of the previous one, it's a new ball
        if row['time'] > last_time + EVENT_COOLDOWN:
            final_events.append(row)
            last_time = row['time']

events_df = pd.DataFrame(final_events)

# Visualization
plt.figure(figsize=(14, 6))
plt.plot(df['time'], df['shooter_velocity'], label='Raw Velocity', color='gray', alpha=0.4)
plt.plot(df['time'], df['filtered_velocity'], label='Filtered (Snapped)', color='blue', linewidth=2)

if not events_df.empty:
    plt.scatter(events_df['time'], events_df['shooter_velocity'],
                color='red', s=200, marker='*', label='Confirmed Ball Event', zorder=30)

plt.title(f'Detected {len(events_df)} Ball Events (Grouping Sequential Drops within {EVENT_COOLDOWN}s)')
plt.xlabel('Time (s)')
plt.ylabel('Velocity')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()

print(f"Total Balls Detected: {len(events_df)}")
display(events_df[['time', 'shooter_velocity', 'raw_velocity_slope']])

import numpy as np

# Calculate the slope (gradient) of the filtered velocity
# np.gradient gives the central difference
df['velocity_slope'] = np.gradient(df['filtered_velocity'], df['time'])

plt.figure(figsize=(14, 8))

# Plot Velocity
plt.subplot(2, 1, 1)
plt.plot(df['time'], df['filtered_velocity'], label='Filtered Velocity', color='blue', marker='o', markersize=3)
plt.title('Velocity vs Slope Analysis')
plt.ylabel('Velocity')
plt.grid(True, alpha=0.3)
plt.legend()

# Plot Slope
plt.subplot(2, 1, 2)
plt.plot(df['time'], df['velocity_slope'], label='Velocity Slope (dv/dt)', color='purple')
plt.axhline(y=0, color='black', linestyle='--', alpha=0.5)
plt.ylabel('Slope (units/sec)')
plt.xlabel('Time (s)')
plt.grid(True, alpha=0.3)
plt.legend()

plt.tight_layout()
plt.show()

display(df[['time', 'filtered_velocity', 'velocity_slope']].head(15))