// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.ChannelValue}
 */
public  final class ChannelValue extends
    com.google.protobuf.GeneratedMessageLite<
        ChannelValue, ChannelValue.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.ChannelValue)
    ChannelValueOrBuilder {
  private ChannelValue() {
  }
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase {
    FLOAT64_VALUE(2),
    INT64_VALUE(3),
    BOOLEAN_VALUE(4),
    STRING_VALUE(5),
    VECTOR2_VALUE(6),
    VECTOR3_VALUE(7),
    POSE2D_VALUE(8),
    UNAVAILABLE(9),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return FLOAT64_VALUE;
        case 3: return INT64_VALUE;
        case 4: return BOOLEAN_VALUE;
        case 5: return STRING_VALUE;
        case 6: return VECTOR2_VALUE;
        case 7: return VECTOR3_VALUE;
        case 8: return POSE2D_VALUE;
        case 9: return UNAVAILABLE;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 1;
  private int channelId_;
  /**
   * <code>uint32 channel_id = 1;</code>
   * @return The channelId.
   */
  @java.lang.Override
  public int getChannelId() {
    return channelId_;
  }
  /**
   * <code>uint32 channel_id = 1;</code>
   * @param value The channelId to set.
   */
  private void setChannelId(int value) {
    
    channelId_ = value;
  }
  /**
   * <code>uint32 channel_id = 1;</code>
   */
  private void clearChannelId() {

    channelId_ = 0;
  }

  public static final int FLOAT64_VALUE_FIELD_NUMBER = 2;
  /**
   * <code>double float64_value = 2;</code>
   * @return Whether the float64Value field is set.
   */
  @java.lang.Override
  public boolean hasFloat64Value() {
    return valueCase_ == 2;
  }
  /**
   * <code>double float64_value = 2;</code>
   * @return The float64Value.
   */
  @java.lang.Override
  public double getFloat64Value() {
    if (valueCase_ == 2) {
      return (java.lang.Double) value_;
    }
    return 0D;
  }
  /**
   * <code>double float64_value = 2;</code>
   * @param value The float64Value to set.
   */
  private void setFloat64Value(double value) {
    valueCase_ = 2;
    value_ = value;
  }
  /**
   * <code>double float64_value = 2;</code>
   */
  private void clearFloat64Value() {
    if (valueCase_ == 2) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int INT64_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>sint64 int64_value = 3;</code>
   * @return Whether the int64Value field is set.
   */
  @java.lang.Override
  public boolean hasInt64Value() {
    return valueCase_ == 3;
  }
  /**
   * <code>sint64 int64_value = 3;</code>
   * @return The int64Value.
   */
  @java.lang.Override
  public long getInt64Value() {
    if (valueCase_ == 3) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }
  /**
   * <code>sint64 int64_value = 3;</code>
   * @param value The int64Value to set.
   */
  private void setInt64Value(long value) {
    valueCase_ = 3;
    value_ = value;
  }
  /**
   * <code>sint64 int64_value = 3;</code>
   */
  private void clearInt64Value() {
    if (valueCase_ == 3) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int BOOLEAN_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>bool boolean_value = 4;</code>
   * @return Whether the booleanValue field is set.
   */
  @java.lang.Override
  public boolean hasBooleanValue() {
    return valueCase_ == 4;
  }
  /**
   * <code>bool boolean_value = 4;</code>
   * @return The booleanValue.
   */
  @java.lang.Override
  public boolean getBooleanValue() {
    if (valueCase_ == 4) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <code>bool boolean_value = 4;</code>
   * @param value The booleanValue to set.
   */
  private void setBooleanValue(boolean value) {
    valueCase_ = 4;
    value_ = value;
  }
  /**
   * <code>bool boolean_value = 4;</code>
   */
  private void clearBooleanValue() {
    if (valueCase_ == 4) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>string string_value = 5;</code>
   * @return Whether the stringValue field is set.
   */
  @java.lang.Override
  public boolean hasStringValue() {
    return valueCase_ == 5;
  }
  /**
   * <code>string string_value = 5;</code>
   * @return The stringValue.
   */
  @java.lang.Override
  public java.lang.String getStringValue() {
    java.lang.String ref = "";
    if (valueCase_ == 5) {
      ref = (java.lang.String) value_;
    }
    return ref;
  }
  /**
   * <code>string string_value = 5;</code>
   * @return The bytes for stringValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.String ref = "";
    if (valueCase_ == 5) {
      ref = (java.lang.String) value_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>string string_value = 5;</code>
   * @param value The stringValue to set.
   */
  private void setStringValue(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  valueCase_ = 5;
    value_ = value;
  }
  /**
   * <code>string string_value = 5;</code>
   */
  private void clearStringValue() {
    if (valueCase_ == 5) {
      valueCase_ = 0;
      value_ = null;
    }
  }
  /**
   * <code>string string_value = 5;</code>
   * @param value The bytes for stringValue to set.
   */
  private void setStringValueBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    value_ = value.toStringUtf8();
    valueCase_ = 5;
  }

  public static final int VECTOR2_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
   */
  @java.lang.Override
  public boolean hasVector2Value() {
    return valueCase_ == 6;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Vector2 getVector2Value() {
    if (valueCase_ == 6) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Vector2) value_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Vector2.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
   */
  private void setVector2Value(org.firstinspires.ftc.teamcode.data.protocol.Vector2 value) {
    value.getClass();
  value_ = value;
    valueCase_ = 6;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
   */
  private void mergeVector2Value(org.firstinspires.ftc.teamcode.data.protocol.Vector2 value) {
    value.getClass();
  if (valueCase_ == 6 &&
        value_ != org.firstinspires.ftc.teamcode.data.protocol.Vector2.getDefaultInstance()) {
      value_ = org.firstinspires.ftc.teamcode.data.protocol.Vector2.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Vector2) value_)
          .mergeFrom(value).buildPartial();
    } else {
      value_ = value;
    }
    valueCase_ = 6;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
   */
  private void clearVector2Value() {
    if (valueCase_ == 6) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int VECTOR3_VALUE_FIELD_NUMBER = 7;
  /**
   * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
   */
  @java.lang.Override
  public boolean hasVector3Value() {
    return valueCase_ == 7;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Vector3 getVector3Value() {
    if (valueCase_ == 7) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Vector3) value_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Vector3.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
   */
  private void setVector3Value(org.firstinspires.ftc.teamcode.data.protocol.Vector3 value) {
    value.getClass();
  value_ = value;
    valueCase_ = 7;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
   */
  private void mergeVector3Value(org.firstinspires.ftc.teamcode.data.protocol.Vector3 value) {
    value.getClass();
  if (valueCase_ == 7 &&
        value_ != org.firstinspires.ftc.teamcode.data.protocol.Vector3.getDefaultInstance()) {
      value_ = org.firstinspires.ftc.teamcode.data.protocol.Vector3.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Vector3) value_)
          .mergeFrom(value).buildPartial();
    } else {
      value_ = value;
    }
    valueCase_ = 7;
  }
  /**
   * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
   */
  private void clearVector3Value() {
    if (valueCase_ == 7) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int POSE2D_VALUE_FIELD_NUMBER = 8;
  /**
   * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
   */
  @java.lang.Override
  public boolean hasPose2DValue() {
    return valueCase_ == 8;
  }
  /**
   * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Pose2d getPose2DValue() {
    if (valueCase_ == 8) {
       return (org.firstinspires.ftc.teamcode.data.protocol.Pose2d) value_;
    }
    return org.firstinspires.ftc.teamcode.data.protocol.Pose2d.getDefaultInstance();
  }
  /**
   * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
   */
  private void setPose2DValue(org.firstinspires.ftc.teamcode.data.protocol.Pose2d value) {
    value.getClass();
  value_ = value;
    valueCase_ = 8;
  }
  /**
   * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
   */
  private void mergePose2DValue(org.firstinspires.ftc.teamcode.data.protocol.Pose2d value) {
    value.getClass();
  if (valueCase_ == 8 &&
        value_ != org.firstinspires.ftc.teamcode.data.protocol.Pose2d.getDefaultInstance()) {
      value_ = org.firstinspires.ftc.teamcode.data.protocol.Pose2d.newBuilder((org.firstinspires.ftc.teamcode.data.protocol.Pose2d) value_)
          .mergeFrom(value).buildPartial();
    } else {
      value_ = value;
    }
    valueCase_ = 8;
  }
  /**
   * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
   */
  private void clearPose2DValue() {
    if (valueCase_ == 8) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int UNAVAILABLE_FIELD_NUMBER = 9;
  /**
   * <pre>
   * must be true when present
   * </pre>
   *
   * <code>bool unavailable = 9;</code>
   * @return Whether the unavailable field is set.
   */
  @java.lang.Override
  public boolean hasUnavailable() {
    return valueCase_ == 9;
  }
  /**
   * <pre>
   * must be true when present
   * </pre>
   *
   * <code>bool unavailable = 9;</code>
   * @return The unavailable.
   */
  @java.lang.Override
  public boolean getUnavailable() {
    if (valueCase_ == 9) {
      return (java.lang.Boolean) value_;
    }
    return false;
  }
  /**
   * <pre>
   * must be true when present
   * </pre>
   *
   * <code>bool unavailable = 9;</code>
   * @param value The unavailable to set.
   */
  private void setUnavailable(boolean value) {
    valueCase_ = 9;
    value_ = value;
  }
  /**
   * <pre>
   * must be true when present
   * </pre>
   *
   * <code>bool unavailable = 9;</code>
   */
  private void clearUnavailable() {
    if (valueCase_ == 9) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.ChannelValue prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.ChannelValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.ChannelValue, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.ChannelValue)
      org.firstinspires.ftc.teamcode.data.protocol.ChannelValueOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.ChannelValue.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <code>uint32 channel_id = 1;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public int getChannelId() {
      return instance.getChannelId();
    }
    /**
     * <code>uint32 channel_id = 1;</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(int value) {
      copyOnWrite();
      instance.setChannelId(value);
      return this;
    }
    /**
     * <code>uint32 channel_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      copyOnWrite();
      instance.clearChannelId();
      return this;
    }

    /**
     * <code>double float64_value = 2;</code>
     * @return Whether the float64Value field is set.
     */
    @java.lang.Override
    public boolean hasFloat64Value() {
      return instance.hasFloat64Value();
    }
    /**
     * <code>double float64_value = 2;</code>
     * @return The float64Value.
     */
    @java.lang.Override
    public double getFloat64Value() {
      return instance.getFloat64Value();
    }
    /**
     * <code>double float64_value = 2;</code>
     * @param value The float64Value to set.
     * @return This builder for chaining.
     */
    public Builder setFloat64Value(double value) {
      copyOnWrite();
      instance.setFloat64Value(value);
      return this;
    }
    /**
     * <code>double float64_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloat64Value() {
      copyOnWrite();
      instance.clearFloat64Value();
      return this;
    }

    /**
     * <code>sint64 int64_value = 3;</code>
     * @return Whether the int64Value field is set.
     */
    @java.lang.Override
    public boolean hasInt64Value() {
      return instance.hasInt64Value();
    }
    /**
     * <code>sint64 int64_value = 3;</code>
     * @return The int64Value.
     */
    @java.lang.Override
    public long getInt64Value() {
      return instance.getInt64Value();
    }
    /**
     * <code>sint64 int64_value = 3;</code>
     * @param value The int64Value to set.
     * @return This builder for chaining.
     */
    public Builder setInt64Value(long value) {
      copyOnWrite();
      instance.setInt64Value(value);
      return this;
    }
    /**
     * <code>sint64 int64_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInt64Value() {
      copyOnWrite();
      instance.clearInt64Value();
      return this;
    }

    /**
     * <code>bool boolean_value = 4;</code>
     * @return Whether the booleanValue field is set.
     */
    @java.lang.Override
    public boolean hasBooleanValue() {
      return instance.hasBooleanValue();
    }
    /**
     * <code>bool boolean_value = 4;</code>
     * @return The booleanValue.
     */
    @java.lang.Override
    public boolean getBooleanValue() {
      return instance.getBooleanValue();
    }
    /**
     * <code>bool boolean_value = 4;</code>
     * @param value The booleanValue to set.
     * @return This builder for chaining.
     */
    public Builder setBooleanValue(boolean value) {
      copyOnWrite();
      instance.setBooleanValue(value);
      return this;
    }
    /**
     * <code>bool boolean_value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBooleanValue() {
      copyOnWrite();
      instance.clearBooleanValue();
      return this;
    }

    /**
     * <code>string string_value = 5;</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return instance.hasStringValue();
    }
    /**
     * <code>string string_value = 5;</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      return instance.getStringValue();
    }
    /**
     * <code>string string_value = 5;</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      return instance.getStringValueBytes();
    }
    /**
     * <code>string string_value = 5;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      copyOnWrite();
      instance.setStringValue(value);
      return this;
    }
    /**
     * <code>string string_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      copyOnWrite();
      instance.clearStringValue();
      return this;
    }
    /**
     * <code>string string_value = 5;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStringValueBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    @java.lang.Override
    public boolean hasVector2Value() {
      return instance.hasVector2Value();
    }
    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Vector2 getVector2Value() {
      return instance.getVector2Value();
    }
    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    public Builder setVector2Value(org.firstinspires.ftc.teamcode.data.protocol.Vector2 value) {
      copyOnWrite();
      instance.setVector2Value(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    public Builder setVector2Value(
        org.firstinspires.ftc.teamcode.data.protocol.Vector2.Builder builderForValue) {
      copyOnWrite();
      instance.setVector2Value(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    public Builder mergeVector2Value(org.firstinspires.ftc.teamcode.data.protocol.Vector2 value) {
      copyOnWrite();
      instance.mergeVector2Value(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector2 vector2_value = 6;</code>
     */
    public Builder clearVector2Value() {
      copyOnWrite();
      instance.clearVector2Value();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    @java.lang.Override
    public boolean hasVector3Value() {
      return instance.hasVector3Value();
    }
    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Vector3 getVector3Value() {
      return instance.getVector3Value();
    }
    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    public Builder setVector3Value(org.firstinspires.ftc.teamcode.data.protocol.Vector3 value) {
      copyOnWrite();
      instance.setVector3Value(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    public Builder setVector3Value(
        org.firstinspires.ftc.teamcode.data.protocol.Vector3.Builder builderForValue) {
      copyOnWrite();
      instance.setVector3Value(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    public Builder mergeVector3Value(org.firstinspires.ftc.teamcode.data.protocol.Vector3 value) {
      copyOnWrite();
      instance.mergeVector3Value(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Vector3 vector3_value = 7;</code>
     */
    public Builder clearVector3Value() {
      copyOnWrite();
      instance.clearVector3Value();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    @java.lang.Override
    public boolean hasPose2DValue() {
      return instance.hasPose2DValue();
    }
    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Pose2d getPose2DValue() {
      return instance.getPose2DValue();
    }
    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    public Builder setPose2DValue(org.firstinspires.ftc.teamcode.data.protocol.Pose2d value) {
      copyOnWrite();
      instance.setPose2DValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    public Builder setPose2DValue(
        org.firstinspires.ftc.teamcode.data.protocol.Pose2d.Builder builderForValue) {
      copyOnWrite();
      instance.setPose2DValue(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    public Builder mergePose2DValue(org.firstinspires.ftc.teamcode.data.protocol.Pose2d value) {
      copyOnWrite();
      instance.mergePose2DValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Pose2d pose2d_value = 8;</code>
     */
    public Builder clearPose2DValue() {
      copyOnWrite();
      instance.clearPose2DValue();
      return this;
    }

    /**
     * <pre>
     * must be true when present
     * </pre>
     *
     * <code>bool unavailable = 9;</code>
     * @return Whether the unavailable field is set.
     */
    @java.lang.Override
    public boolean hasUnavailable() {
      return instance.hasUnavailable();
    }
    /**
     * <pre>
     * must be true when present
     * </pre>
     *
     * <code>bool unavailable = 9;</code>
     * @return The unavailable.
     */
    @java.lang.Override
    public boolean getUnavailable() {
      return instance.getUnavailable();
    }
    /**
     * <pre>
     * must be true when present
     * </pre>
     *
     * <code>bool unavailable = 9;</code>
     * @param value The unavailable to set.
     * @return This builder for chaining.
     */
    public Builder setUnavailable(boolean value) {
      copyOnWrite();
      instance.setUnavailable(value);
      return this;
    }
    /**
     * <pre>
     * must be true when present
     * </pre>
     *
     * <code>bool unavailable = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnavailable() {
      copyOnWrite();
      instance.clearUnavailable();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.ChannelValue)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.ChannelValue();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "valueCase_",
            "channelId_",
            org.firstinspires.ftc.teamcode.data.protocol.Vector2.class,
            org.firstinspires.ftc.teamcode.data.protocol.Vector3.class,
            org.firstinspires.ftc.teamcode.data.protocol.Pose2d.class,
          };
          java.lang.String info =
              "\u0000\t\u0001\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u000b\u00023\u0000\u0003C" +
              "\u0000\u0004:\u0000\u0005\u023b\u0000\u0006<\u0000\u0007<\u0000\b<\u0000\t:\u0000" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.ChannelValue> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.ChannelValue.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.ChannelValue>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.ChannelValue)
  private static final org.firstinspires.ftc.teamcode.data.protocol.ChannelValue DEFAULT_INSTANCE;
  static {
    ChannelValue defaultInstance = new ChannelValue();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ChannelValue.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.ChannelValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ChannelValue> PARSER;

  public static com.google.protobuf.Parser<ChannelValue> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

