// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.Channel}
 */
public  final class Channel extends
    com.google.protobuf.GeneratedMessageLite<
        Channel, Channel.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.Channel)
    ChannelOrBuilder {
  private Channel() {
    key_ = "";
    label_ = "";
    quantity_ = "";
    unit_ = "";
    description_ = "";
  }
  public static final int CHANNEL_ID_FIELD_NUMBER = 1;
  private int channelId_;
  /**
   * <code>uint32 channel_id = 1;</code>
   * @return The channelId.
   */
  @java.lang.Override
  public int getChannelId() {
    return channelId_;
  }
  /**
   * <code>uint32 channel_id = 1;</code>
   * @param value The channelId to set.
   */
  private void setChannelId(int value) {
    
    channelId_ = value;
  }
  /**
   * <code>uint32 channel_id = 1;</code>
   */
  private void clearChannelId() {

    channelId_ = 0;
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private java.lang.String key_;
  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    return key_;
  }
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(key_);
  }
  /**
   * <code>string key = 2;</code>
   * @param value The key to set.
   */
  private void setKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    key_ = value;
  }
  /**
   * <code>string key = 2;</code>
   */
  private void clearKey() {

    key_ = getDefaultInstance().getKey();
  }
  /**
   * <code>string key = 2;</code>
   * @param value The bytes for key to set.
   */
  private void setKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    key_ = value.toStringUtf8();

  }

  public static final int LABEL_FIELD_NUMBER = 3;
  private java.lang.String label_;
  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>string label = 3;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <code>string label = 3;</code>
   */
  private void clearLabel() {

    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>string label = 3;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();

  }

  public static final int DEVICE_ID_FIELD_NUMBER = 4;
  private int deviceId_;
  /**
   * <pre>
   * zero means robot-wide
   * </pre>
   *
   * <code>uint32 device_id = 4;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public int getDeviceId() {
    return deviceId_;
  }
  /**
   * <pre>
   * zero means robot-wide
   * </pre>
   *
   * <code>uint32 device_id = 4;</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(int value) {
    
    deviceId_ = value;
  }
  /**
   * <pre>
   * zero means robot-wide
   * </pre>
   *
   * <code>uint32 device_id = 4;</code>
   */
  private void clearDeviceId() {

    deviceId_ = 0;
  }

  public static final int QUANTITY_FIELD_NUMBER = 5;
  private java.lang.String quantity_;
  /**
   * <code>string quantity = 5;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public java.lang.String getQuantity() {
    return quantity_;
  }
  /**
   * <code>string quantity = 5;</code>
   * @return The bytes for quantity.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuantityBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(quantity_);
  }
  /**
   * <code>string quantity = 5;</code>
   * @param value The quantity to set.
   */
  private void setQuantity(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    quantity_ = value;
  }
  /**
   * <code>string quantity = 5;</code>
   */
  private void clearQuantity() {

    quantity_ = getDefaultInstance().getQuantity();
  }
  /**
   * <code>string quantity = 5;</code>
   * @param value The bytes for quantity to set.
   */
  private void setQuantityBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    quantity_ = value.toStringUtf8();

  }

  public static final int UNIT_FIELD_NUMBER = 6;
  private java.lang.String unit_;
  /**
   * <code>string unit = 6;</code>
   * @return The unit.
   */
  @java.lang.Override
  public java.lang.String getUnit() {
    return unit_;
  }
  /**
   * <code>string unit = 6;</code>
   * @return The bytes for unit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(unit_);
  }
  /**
   * <code>string unit = 6;</code>
   * @param value The unit to set.
   */
  private void setUnit(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    unit_ = value;
  }
  /**
   * <code>string unit = 6;</code>
   */
  private void clearUnit() {

    unit_ = getDefaultInstance().getUnit();
  }
  /**
   * <code>string unit = 6;</code>
   * @param value The bytes for unit to set.
   */
  private void setUnitBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    unit_ = value.toStringUtf8();

  }

  public static final int VALUE_TYPE_FIELD_NUMBER = 7;
  private int valueType_;
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
   * @return The enum numeric value on the wire for valueType.
   */
  @java.lang.Override
  public int getValueTypeValue() {
    return valueType_;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
   * @return The valueType.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.ValueType getValueType() {
    org.firstinspires.ftc.teamcode.data.protocol.ValueType result = org.firstinspires.ftc.teamcode.data.protocol.ValueType.forNumber(valueType_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.ValueType.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
   * @param value The enum numeric value on the wire for valueType to set.
   */
  private void setValueTypeValue(int value) {
      valueType_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
   * @param value The valueType to set.
   */
  private void setValueType(org.firstinspires.ftc.teamcode.data.protocol.ValueType value) {
    valueType_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
   */
  private void clearValueType() {

    valueType_ = 0;
  }

  public static final int ROLE_FIELD_NUMBER = 8;
  private int role_;
  /**
   * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
   * @return The enum numeric value on the wire for role.
   */
  @java.lang.Override
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
   * @return The role.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.ChannelRole getRole() {
    org.firstinspires.ftc.teamcode.data.protocol.ChannelRole result = org.firstinspires.ftc.teamcode.data.protocol.ChannelRole.forNumber(role_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.ChannelRole.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
   * @param value The enum numeric value on the wire for role to set.
   */
  private void setRoleValue(int value) {
      role_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
   * @param value The role to set.
   */
  private void setRole(org.firstinspires.ftc.teamcode.data.protocol.ChannelRole value) {
    role_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
   */
  private void clearRole() {

    role_ = 0;
  }

  public static final int SAMPLE_HINT_HZ_FIELD_NUMBER = 9;
  private double sampleHintHz_;
  /**
   * <pre>
   * zero means unspecified
   * </pre>
   *
   * <code>double sample_hint_hz = 9;</code>
   * @return The sampleHintHz.
   */
  @java.lang.Override
  public double getSampleHintHz() {
    return sampleHintHz_;
  }
  /**
   * <pre>
   * zero means unspecified
   * </pre>
   *
   * <code>double sample_hint_hz = 9;</code>
   * @param value The sampleHintHz to set.
   */
  private void setSampleHintHz(double value) {
    
    sampleHintHz_ = value;
  }
  /**
   * <pre>
   * zero means unspecified
   * </pre>
   *
   * <code>double sample_hint_hz = 9;</code>
   */
  private void clearSampleHintHz() {

    sampleHintHz_ = 0D;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 10;
  private java.lang.String description_;
  /**
   * <code>string description = 10;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 10;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 10;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 10;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 10;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Channel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.Channel prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.Channel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.Channel, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.Channel)
      org.firstinspires.ftc.teamcode.data.protocol.ChannelOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.Channel.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 channel_id = 1;</code>
     * @return The channelId.
     */
    @java.lang.Override
    public int getChannelId() {
      return instance.getChannelId();
    }
    /**
     * <code>uint32 channel_id = 1;</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(int value) {
      copyOnWrite();
      instance.setChannelId(value);
      return this;
    }
    /**
     * <code>uint32 channel_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      copyOnWrite();
      instance.clearChannelId();
      return this;
    }

    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      return instance.getKey();
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      return instance.getKeyBytes();
    }
    /**
     * <code>string key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setKey(value);
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      copyOnWrite();
      instance.clearKey();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyBytes(value);
      return this;
    }

    /**
     * <code>string label = 3;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>string label = 3;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>string label = 3;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <pre>
     * zero means robot-wide
     * </pre>
     *
     * <code>uint32 device_id = 4;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public int getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <pre>
     * zero means robot-wide
     * </pre>
     *
     * <code>uint32 device_id = 4;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(int value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <pre>
     * zero means robot-wide
     * </pre>
     *
     * <code>uint32 device_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }

    /**
     * <code>string quantity = 5;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public java.lang.String getQuantity() {
      return instance.getQuantity();
    }
    /**
     * <code>string quantity = 5;</code>
     * @return The bytes for quantity.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQuantityBytes() {
      return instance.getQuantityBytes();
    }
    /**
     * <code>string quantity = 5;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(
        java.lang.String value) {
      copyOnWrite();
      instance.setQuantity(value);
      return this;
    }
    /**
     * <code>string quantity = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      copyOnWrite();
      instance.clearQuantity();
      return this;
    }
    /**
     * <code>string quantity = 5;</code>
     * @param value The bytes for quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setQuantityBytes(value);
      return this;
    }

    /**
     * <code>string unit = 6;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      return instance.getUnit();
    }
    /**
     * <code>string unit = 6;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      return instance.getUnitBytes();
    }
    /**
     * <code>string unit = 6;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(
        java.lang.String value) {
      copyOnWrite();
      instance.setUnit(value);
      return this;
    }
    /**
     * <code>string unit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      copyOnWrite();
      instance.clearUnit();
      return this;
    }
    /**
     * <code>string unit = 6;</code>
     * @param value The bytes for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUnitBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
     * @return The enum numeric value on the wire for valueType.
     */
    @java.lang.Override
    public int getValueTypeValue() {
      return instance.getValueTypeValue();
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
     * @param value The valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueTypeValue(int value) {
      copyOnWrite();
      instance.setValueTypeValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
     * @return The valueType.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.ValueType getValueType() {
      return instance.getValueType();
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
     * @param value The enum numeric value on the wire for valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueType(org.firstinspires.ftc.teamcode.data.protocol.ValueType value) {
      copyOnWrite();
      instance.setValueType(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueType() {
      copyOnWrite();
      instance.clearValueType();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override
    public int getRoleValue() {
      return instance.getRoleValue();
    }
    /**
     * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      copyOnWrite();
      instance.setRoleValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
     * @return The role.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.ChannelRole getRole() {
      return instance.getRole();
    }
    /**
     * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(org.firstinspires.ftc.teamcode.data.protocol.ChannelRole value) {
      copyOnWrite();
      instance.setRole(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ChannelRole role = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      copyOnWrite();
      instance.clearRole();
      return this;
    }

    /**
     * <pre>
     * zero means unspecified
     * </pre>
     *
     * <code>double sample_hint_hz = 9;</code>
     * @return The sampleHintHz.
     */
    @java.lang.Override
    public double getSampleHintHz() {
      return instance.getSampleHintHz();
    }
    /**
     * <pre>
     * zero means unspecified
     * </pre>
     *
     * <code>double sample_hint_hz = 9;</code>
     * @param value The sampleHintHz to set.
     * @return This builder for chaining.
     */
    public Builder setSampleHintHz(double value) {
      copyOnWrite();
      instance.setSampleHintHz(value);
      return this;
    }
    /**
     * <pre>
     * zero means unspecified
     * </pre>
     *
     * <code>double sample_hint_hz = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleHintHz() {
      copyOnWrite();
      instance.clearSampleHintHz();
      return this;
    }

    /**
     * <code>string description = 10;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 10;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 10;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 10;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.Channel)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.Channel();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "channelId_",
            "key_",
            "label_",
            "deviceId_",
            "quantity_",
            "unit_",
            "valueType_",
            "role_",
            "sampleHintHz_",
            "description_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u000b\u0002\u0208\u0003\u0208" +
              "\u0004\u000b\u0005\u0208\u0006\u0208\u0007\f\b\f\t\u0000\n\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.Channel> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.Channel.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.Channel>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.Channel)
  private static final org.firstinspires.ftc.teamcode.data.protocol.Channel DEFAULT_INSTANCE;
  static {
    Channel defaultInstance = new Channel();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Channel.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Channel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Channel> PARSER;

  public static com.google.protobuf.Parser<Channel> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

