// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf enum {@code ftc.robotdata.v2.DebugCommandResult}
 */
public enum DebugCommandResult
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>DEBUG_COMMAND_RESULT_UNSPECIFIED = 0;</code>
   */
  DEBUG_COMMAND_RESULT_UNSPECIFIED(0),
  /**
   * <code>DEBUG_COMMAND_ACCEPTED = 1;</code>
   */
  DEBUG_COMMAND_ACCEPTED(1),
  /**
   * <code>DEBUG_COMMAND_COMPLETED = 2;</code>
   */
  DEBUG_COMMAND_COMPLETED(2),
  /**
   * <code>DEBUG_COMMAND_REJECTED = 3;</code>
   */
  DEBUG_COMMAND_REJECTED(3),
  /**
   * <code>DEBUG_COMMAND_EXPIRED = 4;</code>
   */
  DEBUG_COMMAND_EXPIRED(4),
  /**
   * <code>DEBUG_COMMAND_DUPLICATE = 5;</code>
   */
  DEBUG_COMMAND_DUPLICATE(5),
  /**
   * <code>DEBUG_COMMAND_FAILED = 6;</code>
   */
  DEBUG_COMMAND_FAILED(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEBUG_COMMAND_RESULT_UNSPECIFIED = 0;</code>
   */
  public static final int DEBUG_COMMAND_RESULT_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEBUG_COMMAND_ACCEPTED = 1;</code>
   */
  public static final int DEBUG_COMMAND_ACCEPTED_VALUE = 1;
  /**
   * <code>DEBUG_COMMAND_COMPLETED = 2;</code>
   */
  public static final int DEBUG_COMMAND_COMPLETED_VALUE = 2;
  /**
   * <code>DEBUG_COMMAND_REJECTED = 3;</code>
   */
  public static final int DEBUG_COMMAND_REJECTED_VALUE = 3;
  /**
   * <code>DEBUG_COMMAND_EXPIRED = 4;</code>
   */
  public static final int DEBUG_COMMAND_EXPIRED_VALUE = 4;
  /**
   * <code>DEBUG_COMMAND_DUPLICATE = 5;</code>
   */
  public static final int DEBUG_COMMAND_DUPLICATE_VALUE = 5;
  /**
   * <code>DEBUG_COMMAND_FAILED = 6;</code>
   */
  public static final int DEBUG_COMMAND_FAILED_VALUE = 6;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DebugCommandResult valueOf(int value) {
    return forNumber(value);
  }

  public static DebugCommandResult forNumber(int value) {
    switch (value) {
      case 0: return DEBUG_COMMAND_RESULT_UNSPECIFIED;
      case 1: return DEBUG_COMMAND_ACCEPTED;
      case 2: return DEBUG_COMMAND_COMPLETED;
      case 3: return DEBUG_COMMAND_REJECTED;
      case 4: return DEBUG_COMMAND_EXPIRED;
      case 5: return DEBUG_COMMAND_DUPLICATE;
      case 6: return DEBUG_COMMAND_FAILED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DebugCommandResult>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DebugCommandResult> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DebugCommandResult>() {
          @java.lang.Override
          public DebugCommandResult findValueByNumber(int number) {
            return DebugCommandResult.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return DebugCommandResultVerifier.INSTANCE;
  }

  private static final class DebugCommandResultVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DebugCommandResultVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return DebugCommandResult.forNumber(number) != null;
          }
        };

  private final int value;

  private DebugCommandResult(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ftc.robotdata.v2.DebugCommandResult)
}

