// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugRunChunk}
 */
public  final class DebugRunChunk extends
    com.google.protobuf.GeneratedMessageLite<
        DebugRunChunk, DebugRunChunk.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugRunChunk)
    DebugRunChunkOrBuilder {
  private DebugRunChunk() {
    runId_ = "";
    samples_ = emptyProtobufList();
  }
  public static final int RUN_ID_FIELD_NUMBER = 1;
  private java.lang.String runId_;
  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    return runId_;
  }
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(runId_);
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The runId to set.
   */
  private void setRunId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    runId_ = value;
  }
  /**
   * <code>string run_id = 1;</code>
   */
  private void clearRunId() {

    runId_ = getDefaultInstance().getRunId();
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The bytes for runId to set.
   */
  private void setRunIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    runId_ = value.toStringUtf8();

  }

  public static final int CHUNK_INDEX_FIELD_NUMBER = 2;
  private int chunkIndex_;
  /**
   * <code>uint32 chunk_index = 2;</code>
   * @return The chunkIndex.
   */
  @java.lang.Override
  public int getChunkIndex() {
    return chunkIndex_;
  }
  /**
   * <code>uint32 chunk_index = 2;</code>
   * @param value The chunkIndex to set.
   */
  private void setChunkIndex(int value) {
    
    chunkIndex_ = value;
  }
  /**
   * <code>uint32 chunk_index = 2;</code>
   */
  private void clearChunkIndex() {

    chunkIndex_ = 0;
  }

  public static final int SAMPLES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> samples_;
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> getSamplesList() {
    return samples_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  public java.util.List<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugRunSampleOrBuilder> 
      getSamplesOrBuilderList() {
    return samples_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  @java.lang.Override
  public int getSamplesCount() {
    return samples_.size();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample getSamples(int index) {
    return samples_.get(index);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  public org.firstinspires.ftc.teamcode.data.protocol.DebugRunSampleOrBuilder getSamplesOrBuilder(
      int index) {
    return samples_.get(index);
  }
  private void ensureSamplesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> tmp = samples_;
    if (!tmp.isModifiable()) {
      samples_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void setSamples(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
    value.getClass();
  ensureSamplesIsMutable();
    samples_.set(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void addSamples(org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
    value.getClass();
  ensureSamplesIsMutable();
    samples_.add(value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void addSamples(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
    value.getClass();
  ensureSamplesIsMutable();
    samples_.add(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void addAllSamples(
      java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> values) {
    ensureSamplesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, samples_);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void clearSamples() {
    samples_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
   */
  private void removeSamples(int index) {
    ensureSamplesIsMutable();
    samples_.remove(index);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugRunChunk}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugRunChunk)
      org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunkOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string run_id = 1;</code>
     * @return The runId.
     */
    @java.lang.Override
    public java.lang.String getRunId() {
      return instance.getRunId();
    }
    /**
     * <code>string run_id = 1;</code>
     * @return The bytes for runId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      return instance.getRunIdBytes();
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRunId(value);
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      copyOnWrite();
      instance.clearRunId();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRunIdBytes(value);
      return this;
    }

    /**
     * <code>uint32 chunk_index = 2;</code>
     * @return The chunkIndex.
     */
    @java.lang.Override
    public int getChunkIndex() {
      return instance.getChunkIndex();
    }
    /**
     * <code>uint32 chunk_index = 2;</code>
     * @param value The chunkIndex to set.
     * @return This builder for chaining.
     */
    public Builder setChunkIndex(int value) {
      copyOnWrite();
      instance.setChunkIndex(value);
      return this;
    }
    /**
     * <code>uint32 chunk_index = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChunkIndex() {
      copyOnWrite();
      instance.clearChunkIndex();
      return this;
    }

    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> getSamplesList() {
      return java.util.Collections.unmodifiableList(
          instance.getSamplesList());
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    @java.lang.Override
    public int getSamplesCount() {
      return instance.getSamplesCount();
    }/**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample getSamples(int index) {
      return instance.getSamples(index);
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder setSamples(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
      copyOnWrite();
      instance.setSamples(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder setSamples(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample.Builder builderForValue) {
      copyOnWrite();
      instance.setSamples(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder addSamples(org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
      copyOnWrite();
      instance.addSamples(value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder addSamples(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample value) {
      copyOnWrite();
      instance.addSamples(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder addSamples(
        org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample.Builder builderForValue) {
      copyOnWrite();
      instance.addSamples(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder addSamples(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample.Builder builderForValue) {
      copyOnWrite();
      instance.addSamples(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder addAllSamples(
        java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample> values) {
      copyOnWrite();
      instance.addAllSamples(values);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder clearSamples() {
      copyOnWrite();
      instance.clearSamples();
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugRunSample samples = 3;</code>
     */
    public Builder removeSamples(int index) {
      copyOnWrite();
      instance.removeSamples(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugRunChunk)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "runId_",
            "chunkIndex_",
            "samples_",
            org.firstinspires.ftc.teamcode.data.protocol.DebugRunSample.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u000b" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugRunChunk)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk DEFAULT_INSTANCE;
  static {
    DebugRunChunk defaultInstance = new DebugRunChunk();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugRunChunk.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugRunChunk> PARSER;

  public static com.google.protobuf.Parser<DebugRunChunk> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

