// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface DebugToolReadyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.DebugToolReady)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string tool_instance_id = 2;</code>
   * @return The toolInstanceId.
   */
  java.lang.String getToolInstanceId();
  /**
   * <code>string tool_instance_id = 2;</code>
   * @return The bytes for toolInstanceId.
   */
  com.google.protobuf.ByteString
      getToolInstanceIdBytes();

  /**
   * <code>uint32 manifest_revision = 3;</code>
   * @return The manifestRevision.
   */
  int getManifestRevision();

  /**
   * <code>repeated .ftc.robotdata.v2.DebugParameter parameters = 4;</code>
   */
  java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugParameter> 
      getParametersList();
  /**
   * <code>repeated .ftc.robotdata.v2.DebugParameter parameters = 4;</code>
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugParameter getParameters(int index);
  /**
   * <code>repeated .ftc.robotdata.v2.DebugParameter parameters = 4;</code>
   */
  int getParametersCount();

  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommand commands = 5;</code>
   */
  java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugCommand> 
      getCommandsList();
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommand commands = 5;</code>
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugCommand getCommands(int index);
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommand commands = 5;</code>
   */
  int getCommandsCount();

  /**
   * <code>repeated string telemetry_channel_ids = 6;</code>
   * @return A list containing the telemetryChannelIds.
   */
  java.util.List<java.lang.String>
      getTelemetryChannelIdsList();
  /**
   * <code>repeated string telemetry_channel_ids = 6;</code>
   * @return The count of telemetryChannelIds.
   */
  int getTelemetryChannelIdsCount();
  /**
   * <code>repeated string telemetry_channel_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The telemetryChannelIds at the given index.
   */
  java.lang.String getTelemetryChannelIds(int index);
  /**
   * <code>repeated string telemetry_channel_ids = 6;</code>
   * @param index The index of the element to return.
   * @return The telemetryChannelIds at the given index.
   */
  com.google.protobuf.ByteString
      getTelemetryChannelIdsBytes(int index);

  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 7;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 7;</code>
   * @return The state.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState getState();

  /**
   * <code>string message = 8;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 8;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .ftc.robotdata.v2.DebugBenchmarkDefinition benchmarks = 9;</code>
   */
  java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition>
      getBenchmarksList();
  /**
   * <code>repeated .ftc.robotdata.v2.DebugBenchmarkDefinition benchmarks = 9;</code>
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition getBenchmarks(int index);
  /**
   * <code>repeated .ftc.robotdata.v2.DebugBenchmarkDefinition benchmarks = 9;</code>
   */
  int getBenchmarksCount();
}
