// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface DebugRunAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.DebugRunAck)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  java.lang.String getRunId();
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  com.google.protobuf.ByteString
      getRunIdBytes();

  /**
   * <code>uint32 total_samples = 2;</code>
   * @return The totalSamples.
   */
  int getTotalSamples();
}
