// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface DebugSelectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.DebugSelectRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>uint32 manifest_revision = 2;</code>
   * @return The manifestRevision.
   */
  int getManifestRevision();

  /**
   * <code>string node_id = 3;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 3;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();
}
