// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugRunAck}
 */
public  final class DebugRunAck extends
    com.google.protobuf.GeneratedMessageLite<
        DebugRunAck, DebugRunAck.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugRunAck)
    DebugRunAckOrBuilder {
  private DebugRunAck() {
    runId_ = "";
  }
  public static final int RUN_ID_FIELD_NUMBER = 1;
  private java.lang.String runId_;
  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    return runId_;
  }
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(runId_);
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The runId to set.
   */
  private void setRunId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    runId_ = value;
  }
  /**
   * <code>string run_id = 1;</code>
   */
  private void clearRunId() {

    runId_ = getDefaultInstance().getRunId();
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The bytes for runId to set.
   */
  private void setRunIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    runId_ = value.toStringUtf8();

  }

  public static final int TOTAL_SAMPLES_FIELD_NUMBER = 2;
  private int totalSamples_;
  /**
   * <code>uint32 total_samples = 2;</code>
   * @return The totalSamples.
   */
  @java.lang.Override
  public int getTotalSamples() {
    return totalSamples_;
  }
  /**
   * <code>uint32 total_samples = 2;</code>
   * @param value The totalSamples to set.
   */
  private void setTotalSamples(int value) {
    
    totalSamples_ = value;
  }
  /**
   * <code>uint32 total_samples = 2;</code>
   */
  private void clearTotalSamples() {

    totalSamples_ = 0;
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugRunAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugRunAck)
      org.firstinspires.ftc.teamcode.data.protocol.DebugRunAckOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string run_id = 1;</code>
     * @return The runId.
     */
    @java.lang.Override
    public java.lang.String getRunId() {
      return instance.getRunId();
    }
    /**
     * <code>string run_id = 1;</code>
     * @return The bytes for runId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      return instance.getRunIdBytes();
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRunId(value);
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      copyOnWrite();
      instance.clearRunId();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRunIdBytes(value);
      return this;
    }

    /**
     * <code>uint32 total_samples = 2;</code>
     * @return The totalSamples.
     */
    @java.lang.Override
    public int getTotalSamples() {
      return instance.getTotalSamples();
    }
    /**
     * <code>uint32 total_samples = 2;</code>
     * @param value The totalSamples to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSamples(int value) {
      copyOnWrite();
      instance.setTotalSamples(value);
      return this;
    }
    /**
     * <code>uint32 total_samples = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalSamples() {
      copyOnWrite();
      instance.clearTotalSamples();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugRunAck)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "runId_",
            "totalSamples_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u000b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugRunAck)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck DEFAULT_INSTANCE;
  static {
    DebugRunAck defaultInstance = new DebugRunAck();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugRunAck.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugRunAck> PARSER;

  public static com.google.protobuf.Parser<DebugRunAck> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

