// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf enum {@code ftc.robotdata.v2.DebugParameterUpdatePolicy}
 */
public enum DebugParameterUpdatePolicy
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>DEBUG_PARAMETER_UPDATE_UNSPECIFIED = 0;</code>
   */
  DEBUG_PARAMETER_UPDATE_UNSPECIFIED(0),
  /**
   * <code>DEBUG_UPDATE_LOOP_BOUNDARY = 1;</code>
   */
  DEBUG_UPDATE_LOOP_BOUNDARY(1),
  /**
   * <code>DEBUG_UPDATE_WHEN_STOPPED = 2;</code>
   */
  DEBUG_UPDATE_WHEN_STOPPED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEBUG_PARAMETER_UPDATE_UNSPECIFIED = 0;</code>
   */
  public static final int DEBUG_PARAMETER_UPDATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEBUG_UPDATE_LOOP_BOUNDARY = 1;</code>
   */
  public static final int DEBUG_UPDATE_LOOP_BOUNDARY_VALUE = 1;
  /**
   * <code>DEBUG_UPDATE_WHEN_STOPPED = 2;</code>
   */
  public static final int DEBUG_UPDATE_WHEN_STOPPED_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DebugParameterUpdatePolicy valueOf(int value) {
    return forNumber(value);
  }

  public static DebugParameterUpdatePolicy forNumber(int value) {
    switch (value) {
      case 0: return DEBUG_PARAMETER_UPDATE_UNSPECIFIED;
      case 1: return DEBUG_UPDATE_LOOP_BOUNDARY;
      case 2: return DEBUG_UPDATE_WHEN_STOPPED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DebugParameterUpdatePolicy>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DebugParameterUpdatePolicy> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DebugParameterUpdatePolicy>() {
          @java.lang.Override
          public DebugParameterUpdatePolicy findValueByNumber(int number) {
            return DebugParameterUpdatePolicy.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return DebugParameterUpdatePolicyVerifier.INSTANCE;
  }

  private static final class DebugParameterUpdatePolicyVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DebugParameterUpdatePolicyVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return DebugParameterUpdatePolicy.forNumber(number) != null;
          }
        };

  private final int value;

  private DebugParameterUpdatePolicy(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ftc.robotdata.v2.DebugParameterUpdatePolicy)
}

