// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugCommandArgumentDefinition}
 */
public  final class DebugCommandArgumentDefinition extends
    com.google.protobuf.GeneratedMessageLite<
        DebugCommandArgumentDefinition, DebugCommandArgumentDefinition.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugCommandArgumentDefinition)
    DebugCommandArgumentDefinitionOrBuilder {
  private DebugCommandArgumentDefinition() {
    id_ = "";
    label_ = "";
    description_ = "";
    unit_ = "";
    enumOptions_ = emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 1;</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private java.lang.String label_;
  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>string label = 2;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <code>string label = 2;</code>
   */
  private void clearLabel() {

    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>string label = 2;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private java.lang.String description_;
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 3;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 3;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 3;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int VALUE_TYPE_FIELD_NUMBER = 4;
  private int valueType_;
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
   * @return The enum numeric value on the wire for valueType.
   */
  @java.lang.Override
  public int getValueTypeValue() {
    return valueType_;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
   * @return The valueType.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.ValueType getValueType() {
    org.firstinspires.ftc.teamcode.data.protocol.ValueType result = org.firstinspires.ftc.teamcode.data.protocol.ValueType.forNumber(valueType_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.ValueType.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
   * @param value The enum numeric value on the wire for valueType to set.
   */
  private void setValueTypeValue(int value) {
      valueType_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
   * @param value The valueType to set.
   */
  private void setValueType(org.firstinspires.ftc.teamcode.data.protocol.ValueType value) {
    valueType_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
   */
  private void clearValueType() {

    valueType_ = 0;
  }

  public static final int REQUIRED_FIELD_NUMBER = 5;
  private boolean required_;
  /**
   * <code>bool required = 5;</code>
   * @return The required.
   */
  @java.lang.Override
  public boolean getRequired() {
    return required_;
  }
  /**
   * <code>bool required = 5;</code>
   * @param value The required to set.
   */
  private void setRequired(boolean value) {
    
    required_ = value;
  }
  /**
   * <code>bool required = 5;</code>
   */
  private void clearRequired() {

    required_ = false;
  }

  public static final int UNIT_FIELD_NUMBER = 6;
  private java.lang.String unit_;
  /**
   * <code>string unit = 6;</code>
   * @return The unit.
   */
  @java.lang.Override
  public java.lang.String getUnit() {
    return unit_;
  }
  /**
   * <code>string unit = 6;</code>
   * @return The bytes for unit.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUnitBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(unit_);
  }
  /**
   * <code>string unit = 6;</code>
   * @param value The unit to set.
   */
  private void setUnit(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    unit_ = value;
  }
  /**
   * <code>string unit = 6;</code>
   */
  private void clearUnit() {

    unit_ = getDefaultInstance().getUnit();
  }
  /**
   * <code>string unit = 6;</code>
   * @param value The bytes for unit to set.
   */
  private void setUnitBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    unit_ = value.toStringUtf8();

  }

  public static final int MIN_FLOAT64_FIELD_NUMBER = 7;
  private double minFloat64_;
  /**
   * <code>double min_float64 = 7;</code>
   * @return The minFloat64.
   */
  @java.lang.Override
  public double getMinFloat64() {
    return minFloat64_;
  }
  /**
   * <code>double min_float64 = 7;</code>
   * @param value The minFloat64 to set.
   */
  private void setMinFloat64(double value) {
    
    minFloat64_ = value;
  }
  /**
   * <code>double min_float64 = 7;</code>
   */
  private void clearMinFloat64() {

    minFloat64_ = 0D;
  }

  public static final int MAX_FLOAT64_FIELD_NUMBER = 8;
  private double maxFloat64_;
  /**
   * <code>double max_float64 = 8;</code>
   * @return The maxFloat64.
   */
  @java.lang.Override
  public double getMaxFloat64() {
    return maxFloat64_;
  }
  /**
   * <code>double max_float64 = 8;</code>
   * @param value The maxFloat64 to set.
   */
  private void setMaxFloat64(double value) {
    
    maxFloat64_ = value;
  }
  /**
   * <code>double max_float64 = 8;</code>
   */
  private void clearMaxFloat64() {

    maxFloat64_ = 0D;
  }

  public static final int ENUM_OPTIONS_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> enumOptions_;
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  @java.lang.Override
  public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> getEnumOptionsList() {
    return enumOptions_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  public java.util.List<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOptionOrBuilder> 
      getEnumOptionsOrBuilderList() {
    return enumOptions_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  @java.lang.Override
  public int getEnumOptionsCount() {
    return enumOptions_.size();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption getEnumOptions(int index) {
    return enumOptions_.get(index);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  public org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOptionOrBuilder getEnumOptionsOrBuilder(
      int index) {
    return enumOptions_.get(index);
  }
  private void ensureEnumOptionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> tmp = enumOptions_;
    if (!tmp.isModifiable()) {
      enumOptions_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void setEnumOptions(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
    value.getClass();
  ensureEnumOptionsIsMutable();
    enumOptions_.set(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void addEnumOptions(org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
    value.getClass();
  ensureEnumOptionsIsMutable();
    enumOptions_.add(value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void addEnumOptions(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
    value.getClass();
  ensureEnumOptionsIsMutable();
    enumOptions_.add(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void addAllEnumOptions(
      java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> values) {
    ensureEnumOptionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, enumOptions_);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void clearEnumOptions() {
    enumOptions_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
   */
  private void removeEnumOptions(int index) {
    ensureEnumOptionsIsMutable();
    enumOptions_.remove(index);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugCommandArgumentDefinition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugCommandArgumentDefinition)
      org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinitionOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string label = 2;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
     * @return The enum numeric value on the wire for valueType.
     */
    @java.lang.Override
    public int getValueTypeValue() {
      return instance.getValueTypeValue();
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
     * @param value The valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueTypeValue(int value) {
      copyOnWrite();
      instance.setValueTypeValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
     * @return The valueType.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.ValueType getValueType() {
      return instance.getValueType();
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
     * @param value The enum numeric value on the wire for valueType to set.
     * @return This builder for chaining.
     */
    public Builder setValueType(org.firstinspires.ftc.teamcode.data.protocol.ValueType value) {
      copyOnWrite();
      instance.setValueType(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.ValueType value_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueType() {
      copyOnWrite();
      instance.clearValueType();
      return this;
    }

    /**
     * <code>bool required = 5;</code>
     * @return The required.
     */
    @java.lang.Override
    public boolean getRequired() {
      return instance.getRequired();
    }
    /**
     * <code>bool required = 5;</code>
     * @param value The required to set.
     * @return This builder for chaining.
     */
    public Builder setRequired(boolean value) {
      copyOnWrite();
      instance.setRequired(value);
      return this;
    }
    /**
     * <code>bool required = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequired() {
      copyOnWrite();
      instance.clearRequired();
      return this;
    }

    /**
     * <code>string unit = 6;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      return instance.getUnit();
    }
    /**
     * <code>string unit = 6;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      return instance.getUnitBytes();
    }
    /**
     * <code>string unit = 6;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(
        java.lang.String value) {
      copyOnWrite();
      instance.setUnit(value);
      return this;
    }
    /**
     * <code>string unit = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      copyOnWrite();
      instance.clearUnit();
      return this;
    }
    /**
     * <code>string unit = 6;</code>
     * @param value The bytes for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUnitBytes(value);
      return this;
    }

    /**
     * <code>double min_float64 = 7;</code>
     * @return The minFloat64.
     */
    @java.lang.Override
    public double getMinFloat64() {
      return instance.getMinFloat64();
    }
    /**
     * <code>double min_float64 = 7;</code>
     * @param value The minFloat64 to set.
     * @return This builder for chaining.
     */
    public Builder setMinFloat64(double value) {
      copyOnWrite();
      instance.setMinFloat64(value);
      return this;
    }
    /**
     * <code>double min_float64 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinFloat64() {
      copyOnWrite();
      instance.clearMinFloat64();
      return this;
    }

    /**
     * <code>double max_float64 = 8;</code>
     * @return The maxFloat64.
     */
    @java.lang.Override
    public double getMaxFloat64() {
      return instance.getMaxFloat64();
    }
    /**
     * <code>double max_float64 = 8;</code>
     * @param value The maxFloat64 to set.
     * @return This builder for chaining.
     */
    public Builder setMaxFloat64(double value) {
      copyOnWrite();
      instance.setMaxFloat64(value);
      return this;
    }
    /**
     * <code>double max_float64 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxFloat64() {
      copyOnWrite();
      instance.clearMaxFloat64();
      return this;
    }

    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    @java.lang.Override
    public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> getEnumOptionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getEnumOptionsList());
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    @java.lang.Override
    public int getEnumOptionsCount() {
      return instance.getEnumOptionsCount();
    }/**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption getEnumOptions(int index) {
      return instance.getEnumOptions(index);
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder setEnumOptions(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
      copyOnWrite();
      instance.setEnumOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder setEnumOptions(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption.Builder builderForValue) {
      copyOnWrite();
      instance.setEnumOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder addEnumOptions(org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
      copyOnWrite();
      instance.addEnumOptions(value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder addEnumOptions(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption value) {
      copyOnWrite();
      instance.addEnumOptions(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder addEnumOptions(
        org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumOptions(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder addEnumOptions(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption.Builder builderForValue) {
      copyOnWrite();
      instance.addEnumOptions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder addAllEnumOptions(
        java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption> values) {
      copyOnWrite();
      instance.addAllEnumOptions(values);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder clearEnumOptions() {
      copyOnWrite();
      instance.clearEnumOptions();
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugEnumOption enum_options = 9;</code>
     */
    public Builder removeEnumOptions(int index) {
      copyOnWrite();
      instance.removeEnumOptions(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugCommandArgumentDefinition)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "label_",
            "description_",
            "valueType_",
            "required_",
            "unit_",
            "minFloat64_",
            "maxFloat64_",
            "enumOptions_",
            org.firstinspires.ftc.teamcode.data.protocol.DebugEnumOption.class,
          };
          java.lang.String info =
              "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0001\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\f\u0005\u0007\u0006\u0208\u0007\u0000\b\u0000\t\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugCommandArgumentDefinition)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition DEFAULT_INSTANCE;
  static {
    DebugCommandArgumentDefinition defaultInstance = new DebugCommandArgumentDefinition();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugCommandArgumentDefinition.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentDefinition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugCommandArgumentDefinition> PARSER;

  public static com.google.protobuf.Parser<DebugCommandArgumentDefinition> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

