// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugRunStatus}
 */
public  final class DebugRunStatus extends
    com.google.protobuf.GeneratedMessageLite<
        DebugRunStatus, DebugRunStatus.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugRunStatus)
    DebugRunStatusOrBuilder {
  private DebugRunStatus() {
    runId_ = "";
    state_ = "";
    phase_ = "";
    message_ = "";
  }
  public static final int RUN_ID_FIELD_NUMBER = 1;
  private java.lang.String runId_;
  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    return runId_;
  }
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(runId_);
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The runId to set.
   */
  private void setRunId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    runId_ = value;
  }
  /**
   * <code>string run_id = 1;</code>
   */
  private void clearRunId() {

    runId_ = getDefaultInstance().getRunId();
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The bytes for runId to set.
   */
  private void setRunIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    runId_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 2;
  private java.lang.String state_;
  /**
   * <code>string state = 2;</code>
   * @return The state.
   */
  @java.lang.Override
  public java.lang.String getState() {
    return state_;
  }
  /**
   * <code>string state = 2;</code>
   * @return The bytes for state.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(state_);
  }
  /**
   * <code>string state = 2;</code>
   * @param value The state to set.
   */
  private void setState(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    state_ = value;
  }
  /**
   * <code>string state = 2;</code>
   */
  private void clearState() {

    state_ = getDefaultInstance().getState();
  }
  /**
   * <code>string state = 2;</code>
   * @param value The bytes for state to set.
   */
  private void setStateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    state_ = value.toStringUtf8();

  }

  public static final int PHASE_FIELD_NUMBER = 3;
  private java.lang.String phase_;
  /**
   * <code>string phase = 3;</code>
   * @return The phase.
   */
  @java.lang.Override
  public java.lang.String getPhase() {
    return phase_;
  }
  /**
   * <code>string phase = 3;</code>
   * @return The bytes for phase.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhaseBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(phase_);
  }
  /**
   * <code>string phase = 3;</code>
   * @param value The phase to set.
   */
  private void setPhase(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    phase_ = value;
  }
  /**
   * <code>string phase = 3;</code>
   */
  private void clearPhase() {

    phase_ = getDefaultInstance().getPhase();
  }
  /**
   * <code>string phase = 3;</code>
   * @param value The bytes for phase to set.
   */
  private void setPhaseBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    phase_ = value.toStringUtf8();

  }

  public static final int REPETITION_FIELD_NUMBER = 4;
  private int repetition_;
  /**
   * <code>uint32 repetition = 4;</code>
   * @return The repetition.
   */
  @java.lang.Override
  public int getRepetition() {
    return repetition_;
  }
  /**
   * <code>uint32 repetition = 4;</code>
   * @param value The repetition to set.
   */
  private void setRepetition(int value) {
    
    repetition_ = value;
  }
  /**
   * <code>uint32 repetition = 4;</code>
   */
  private void clearRepetition() {

    repetition_ = 0;
  }

  public static final int DIRECTION_FIELD_NUMBER = 5;
  private int direction_;
  /**
   * <code>sint32 direction = 5;</code>
   * @return The direction.
   */
  @java.lang.Override
  public int getDirection() {
    return direction_;
  }
  /**
   * <code>sint32 direction = 5;</code>
   * @param value The direction to set.
   */
  private void setDirection(int value) {
    
    direction_ = value;
  }
  /**
   * <code>sint32 direction = 5;</code>
   */
  private void clearDirection() {

    direction_ = 0;
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private java.lang.String message_;
  /**
   * <code>string message = 6;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>string message = 6;</code>
   * @param value The message to set.
   */
  private void setMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    message_ = value;
  }
  /**
   * <code>string message = 6;</code>
   */
  private void clearMessage() {

    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>string message = 6;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugRunStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugRunStatus)
      org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatusOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string run_id = 1;</code>
     * @return The runId.
     */
    @java.lang.Override
    public java.lang.String getRunId() {
      return instance.getRunId();
    }
    /**
     * <code>string run_id = 1;</code>
     * @return The bytes for runId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      return instance.getRunIdBytes();
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRunId(value);
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      copyOnWrite();
      instance.clearRunId();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRunIdBytes(value);
      return this;
    }

    /**
     * <code>string state = 2;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      return instance.getState();
    }
    /**
     * <code>string state = 2;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      return instance.getStateBytes();
    }
    /**
     * <code>string state = 2;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(
        java.lang.String value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>string state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }
    /**
     * <code>string state = 2;</code>
     * @param value The bytes for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStateBytes(value);
      return this;
    }

    /**
     * <code>string phase = 3;</code>
     * @return The phase.
     */
    @java.lang.Override
    public java.lang.String getPhase() {
      return instance.getPhase();
    }
    /**
     * <code>string phase = 3;</code>
     * @return The bytes for phase.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhaseBytes() {
      return instance.getPhaseBytes();
    }
    /**
     * <code>string phase = 3;</code>
     * @param value The phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhase(
        java.lang.String value) {
      copyOnWrite();
      instance.setPhase(value);
      return this;
    }
    /**
     * <code>string phase = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhase() {
      copyOnWrite();
      instance.clearPhase();
      return this;
    }
    /**
     * <code>string phase = 3;</code>
     * @param value The bytes for phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhaseBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPhaseBytes(value);
      return this;
    }

    /**
     * <code>uint32 repetition = 4;</code>
     * @return The repetition.
     */
    @java.lang.Override
    public int getRepetition() {
      return instance.getRepetition();
    }
    /**
     * <code>uint32 repetition = 4;</code>
     * @param value The repetition to set.
     * @return This builder for chaining.
     */
    public Builder setRepetition(int value) {
      copyOnWrite();
      instance.setRepetition(value);
      return this;
    }
    /**
     * <code>uint32 repetition = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRepetition() {
      copyOnWrite();
      instance.clearRepetition();
      return this;
    }

    /**
     * <code>sint32 direction = 5;</code>
     * @return The direction.
     */
    @java.lang.Override
    public int getDirection() {
      return instance.getDirection();
    }
    /**
     * <code>sint32 direction = 5;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(int value) {
      copyOnWrite();
      instance.setDirection(value);
      return this;
    }
    /**
     * <code>sint32 direction = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      copyOnWrite();
      instance.clearDirection();
      return this;
    }

    /**
     * <code>string message = 6;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>string message = 6;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>string message = 6;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugRunStatus)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "runId_",
            "state_",
            "phase_",
            "repetition_",
            "direction_",
            "message_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u000b\u0005\u000f\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugRunStatus)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus DEFAULT_INSTANCE;
  static {
    DebugRunStatus defaultInstance = new DebugRunStatus();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugRunStatus.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugRunStatus> PARSER;

  public static com.google.protobuf.Parser<DebugRunStatus> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

