// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugRunHeader}
 */
public  final class DebugRunHeader extends
    com.google.protobuf.GeneratedMessageLite<
        DebugRunHeader, DebugRunHeader.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugRunHeader)
    DebugRunHeaderOrBuilder {
  private DebugRunHeader() {
    runId_ = "";
    mechanismId_ = "";
    mechanismLabel_ = "";
    motorName_ = "";
    inputs_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int RUN_ID_FIELD_NUMBER = 1;
  private java.lang.String runId_;
  /**
   * <code>string run_id = 1;</code>
   * @return The runId.
   */
  @java.lang.Override
  public java.lang.String getRunId() {
    return runId_;
  }
  /**
   * <code>string run_id = 1;</code>
   * @return The bytes for runId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRunIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(runId_);
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The runId to set.
   */
  private void setRunId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    runId_ = value;
  }
  /**
   * <code>string run_id = 1;</code>
   */
  private void clearRunId() {

    runId_ = getDefaultInstance().getRunId();
  }
  /**
   * <code>string run_id = 1;</code>
   * @param value The bytes for runId to set.
   */
  private void setRunIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    runId_ = value.toStringUtf8();

  }

  public static final int MECHANISM_ID_FIELD_NUMBER = 2;
  private java.lang.String mechanismId_;
  /**
   * <code>string mechanism_id = 2;</code>
   * @return The mechanismId.
   */
  @java.lang.Override
  public java.lang.String getMechanismId() {
    return mechanismId_;
  }
  /**
   * <code>string mechanism_id = 2;</code>
   * @return The bytes for mechanismId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMechanismIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mechanismId_);
  }
  /**
   * <code>string mechanism_id = 2;</code>
   * @param value The mechanismId to set.
   */
  private void setMechanismId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    mechanismId_ = value;
  }
  /**
   * <code>string mechanism_id = 2;</code>
   */
  private void clearMechanismId() {

    mechanismId_ = getDefaultInstance().getMechanismId();
  }
  /**
   * <code>string mechanism_id = 2;</code>
   * @param value The bytes for mechanismId to set.
   */
  private void setMechanismIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mechanismId_ = value.toStringUtf8();

  }

  public static final int MECHANISM_LABEL_FIELD_NUMBER = 3;
  private java.lang.String mechanismLabel_;
  /**
   * <code>string mechanism_label = 3;</code>
   * @return The mechanismLabel.
   */
  @java.lang.Override
  public java.lang.String getMechanismLabel() {
    return mechanismLabel_;
  }
  /**
   * <code>string mechanism_label = 3;</code>
   * @return The bytes for mechanismLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMechanismLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mechanismLabel_);
  }
  /**
   * <code>string mechanism_label = 3;</code>
   * @param value The mechanismLabel to set.
   */
  private void setMechanismLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    mechanismLabel_ = value;
  }
  /**
   * <code>string mechanism_label = 3;</code>
   */
  private void clearMechanismLabel() {

    mechanismLabel_ = getDefaultInstance().getMechanismLabel();
  }
  /**
   * <code>string mechanism_label = 3;</code>
   * @param value The bytes for mechanismLabel to set.
   */
  private void setMechanismLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mechanismLabel_ = value.toStringUtf8();

  }

  public static final int MOTOR_NAME_FIELD_NUMBER = 4;
  private java.lang.String motorName_;
  /**
   * <code>string motor_name = 4;</code>
   * @return The motorName.
   */
  @java.lang.Override
  public java.lang.String getMotorName() {
    return motorName_;
  }
  /**
   * <code>string motor_name = 4;</code>
   * @return The bytes for motorName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMotorNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(motorName_);
  }
  /**
   * <code>string motor_name = 4;</code>
   * @param value The motorName to set.
   */
  private void setMotorName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    motorName_ = value;
  }
  /**
   * <code>string motor_name = 4;</code>
   */
  private void clearMotorName() {

    motorName_ = getDefaultInstance().getMotorName();
  }
  /**
   * <code>string motor_name = 4;</code>
   * @param value The bytes for motorName to set.
   */
  private void setMotorNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    motorName_ = value.toStringUtf8();

  }

  public static final int BENCHMARK_FIELD_NUMBER = 5;
  private org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition benchmark_;
  /**
   * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
   */
  @java.lang.Override
  public boolean hasBenchmark() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition getBenchmark() {
    return benchmark_ == null ? org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition.getDefaultInstance() : benchmark_;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
   */
  private void setBenchmark(org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition value) {
    value.getClass();
  benchmark_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBenchmark(org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition value) {
    value.getClass();
  if (benchmark_ != null &&
        benchmark_ != org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition.getDefaultInstance()) {
      benchmark_ =
        org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition.newBuilder(benchmark_).mergeFrom(value).buildPartial();
    } else {
      benchmark_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
   */
  private void clearBenchmark() {  benchmark_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int INPUTS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> inputs_;
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  @java.lang.Override
  public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> getInputsList() {
    return inputs_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  public java.util.List<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValueOrBuilder> 
      getInputsOrBuilderList() {
    return inputs_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  @java.lang.Override
  public int getInputsCount() {
    return inputs_.size();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue getInputs(int index) {
    return inputs_.get(index);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  public org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValueOrBuilder getInputsOrBuilder(
      int index) {
    return inputs_.get(index);
  }
  private void ensureInputsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> tmp = inputs_;
    if (!tmp.isModifiable()) {
      inputs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void setInputs(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
    value.getClass();
  ensureInputsIsMutable();
    inputs_.set(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void addInputs(org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
    value.getClass();
  ensureInputsIsMutable();
    inputs_.add(value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void addInputs(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
    value.getClass();
  ensureInputsIsMutable();
    inputs_.add(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void addAllInputs(
      java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> values) {
    ensureInputsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, inputs_);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void clearInputs() {
    inputs_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
   */
  private void removeInputs(int index) {
    ensureInputsIsMutable();
    inputs_.remove(index);
  }

  public static final int TICKS_PER_REVOLUTION_FIELD_NUMBER = 7;
  private double ticksPerRevolution_;
  /**
   * <pre>
   * Zero means calibration unavailable.
   * </pre>
   *
   * <code>double ticks_per_revolution = 7;</code>
   * @return The ticksPerRevolution.
   */
  @java.lang.Override
  public double getTicksPerRevolution() {
    return ticksPerRevolution_;
  }
  /**
   * <pre>
   * Zero means calibration unavailable.
   * </pre>
   *
   * <code>double ticks_per_revolution = 7;</code>
   * @param value The ticksPerRevolution to set.
   */
  private void setTicksPerRevolution(double value) {
    
    ticksPerRevolution_ = value;
  }
  /**
   * <pre>
   * Zero means calibration unavailable.
   * </pre>
   *
   * <code>double ticks_per_revolution = 7;</code>
   */
  private void clearTicksPerRevolution() {

    ticksPerRevolution_ = 0D;
  }

  public static final int STARTED_ROBOT_NS_FIELD_NUMBER = 8;
  private long startedRobotNs_;
  /**
   * <code>uint64 started_robot_ns = 8;</code>
   * @return The startedRobotNs.
   */
  @java.lang.Override
  public long getStartedRobotNs() {
    return startedRobotNs_;
  }
  /**
   * <code>uint64 started_robot_ns = 8;</code>
   * @param value The startedRobotNs to set.
   */
  private void setStartedRobotNs(long value) {
    
    startedRobotNs_ = value;
  }
  /**
   * <code>uint64 started_robot_ns = 8;</code>
   */
  private void clearStartedRobotNs() {

    startedRobotNs_ = 0L;
  }

  public static final int MAX_POWER_FIELD_NUMBER = 9;
  private double maxPower_;
  /**
   * <code>double max_power = 9;</code>
   * @return The maxPower.
   */
  @java.lang.Override
  public double getMaxPower() {
    return maxPower_;
  }
  /**
   * <code>double max_power = 9;</code>
   * @param value The maxPower to set.
   */
  private void setMaxPower(double value) {
    
    maxPower_ = value;
  }
  /**
   * <code>double max_power = 9;</code>
   */
  private void clearMaxPower() {

    maxPower_ = 0D;
  }

  public static final int CURRENT_LIMIT_AMPS_FIELD_NUMBER = 10;
  private double currentLimitAmps_;
  /**
   * <code>double current_limit_amps = 10;</code>
   * @return The currentLimitAmps.
   */
  @java.lang.Override
  public double getCurrentLimitAmps() {
    return currentLimitAmps_;
  }
  /**
   * <code>double current_limit_amps = 10;</code>
   * @param value The currentLimitAmps to set.
   */
  private void setCurrentLimitAmps(double value) {
    
    currentLimitAmps_ = value;
  }
  /**
   * <code>double current_limit_amps = 10;</code>
   */
  private void clearCurrentLimitAmps() {

    currentLimitAmps_ = 0D;
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugRunHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugRunHeader)
      org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeaderOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string run_id = 1;</code>
     * @return The runId.
     */
    @java.lang.Override
    public java.lang.String getRunId() {
      return instance.getRunId();
    }
    /**
     * <code>string run_id = 1;</code>
     * @return The bytes for runId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRunIdBytes() {
      return instance.getRunIdBytes();
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRunId(value);
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRunId() {
      copyOnWrite();
      instance.clearRunId();
      return this;
    }
    /**
     * <code>string run_id = 1;</code>
     * @param value The bytes for runId to set.
     * @return This builder for chaining.
     */
    public Builder setRunIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRunIdBytes(value);
      return this;
    }

    /**
     * <code>string mechanism_id = 2;</code>
     * @return The mechanismId.
     */
    @java.lang.Override
    public java.lang.String getMechanismId() {
      return instance.getMechanismId();
    }
    /**
     * <code>string mechanism_id = 2;</code>
     * @return The bytes for mechanismId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMechanismIdBytes() {
      return instance.getMechanismIdBytes();
    }
    /**
     * <code>string mechanism_id = 2;</code>
     * @param value The mechanismId to set.
     * @return This builder for chaining.
     */
    public Builder setMechanismId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMechanismId(value);
      return this;
    }
    /**
     * <code>string mechanism_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMechanismId() {
      copyOnWrite();
      instance.clearMechanismId();
      return this;
    }
    /**
     * <code>string mechanism_id = 2;</code>
     * @param value The bytes for mechanismId to set.
     * @return This builder for chaining.
     */
    public Builder setMechanismIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMechanismIdBytes(value);
      return this;
    }

    /**
     * <code>string mechanism_label = 3;</code>
     * @return The mechanismLabel.
     */
    @java.lang.Override
    public java.lang.String getMechanismLabel() {
      return instance.getMechanismLabel();
    }
    /**
     * <code>string mechanism_label = 3;</code>
     * @return The bytes for mechanismLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMechanismLabelBytes() {
      return instance.getMechanismLabelBytes();
    }
    /**
     * <code>string mechanism_label = 3;</code>
     * @param value The mechanismLabel to set.
     * @return This builder for chaining.
     */
    public Builder setMechanismLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setMechanismLabel(value);
      return this;
    }
    /**
     * <code>string mechanism_label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMechanismLabel() {
      copyOnWrite();
      instance.clearMechanismLabel();
      return this;
    }
    /**
     * <code>string mechanism_label = 3;</code>
     * @param value The bytes for mechanismLabel to set.
     * @return This builder for chaining.
     */
    public Builder setMechanismLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMechanismLabelBytes(value);
      return this;
    }

    /**
     * <code>string motor_name = 4;</code>
     * @return The motorName.
     */
    @java.lang.Override
    public java.lang.String getMotorName() {
      return instance.getMotorName();
    }
    /**
     * <code>string motor_name = 4;</code>
     * @return The bytes for motorName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMotorNameBytes() {
      return instance.getMotorNameBytes();
    }
    /**
     * <code>string motor_name = 4;</code>
     * @param value The motorName to set.
     * @return This builder for chaining.
     */
    public Builder setMotorName(
        java.lang.String value) {
      copyOnWrite();
      instance.setMotorName(value);
      return this;
    }
    /**
     * <code>string motor_name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMotorName() {
      copyOnWrite();
      instance.clearMotorName();
      return this;
    }
    /**
     * <code>string motor_name = 4;</code>
     * @param value The bytes for motorName to set.
     * @return This builder for chaining.
     */
    public Builder setMotorNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMotorNameBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    @java.lang.Override
    public boolean hasBenchmark() {
      return instance.hasBenchmark();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition getBenchmark() {
      return instance.getBenchmark();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    public Builder setBenchmark(org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition value) {
      copyOnWrite();
      instance.setBenchmark(value);
      return this;
      }
    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    public Builder setBenchmark(
        org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition.Builder builderForValue) {
      copyOnWrite();
      instance.setBenchmark(builderForValue.build());
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    public Builder mergeBenchmark(org.firstinspires.ftc.teamcode.data.protocol.DebugBenchmarkDefinition value) {
      copyOnWrite();
      instance.mergeBenchmark(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugBenchmarkDefinition benchmark = 5;</code>
     */
    public Builder clearBenchmark() {  copyOnWrite();
      instance.clearBenchmark();
      return this;
    }

    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    @java.lang.Override
    public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> getInputsList() {
      return java.util.Collections.unmodifiableList(
          instance.getInputsList());
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    @java.lang.Override
    public int getInputsCount() {
      return instance.getInputsCount();
    }/**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue getInputs(int index) {
      return instance.getInputs(index);
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder setInputs(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
      copyOnWrite();
      instance.setInputs(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder setInputs(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue.Builder builderForValue) {
      copyOnWrite();
      instance.setInputs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder addInputs(org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
      copyOnWrite();
      instance.addInputs(value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder addInputs(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue value) {
      copyOnWrite();
      instance.addInputs(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder addInputs(
        org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue.Builder builderForValue) {
      copyOnWrite();
      instance.addInputs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder addInputs(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue.Builder builderForValue) {
      copyOnWrite();
      instance.addInputs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder addAllInputs(
        java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> values) {
      copyOnWrite();
      instance.addAllInputs(values);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder clearInputs() {
      copyOnWrite();
      instance.clearInputs();
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue inputs = 6;</code>
     */
    public Builder removeInputs(int index) {
      copyOnWrite();
      instance.removeInputs(index);
      return this;
    }

    /**
     * <pre>
     * Zero means calibration unavailable.
     * </pre>
     *
     * <code>double ticks_per_revolution = 7;</code>
     * @return The ticksPerRevolution.
     */
    @java.lang.Override
    public double getTicksPerRevolution() {
      return instance.getTicksPerRevolution();
    }
    /**
     * <pre>
     * Zero means calibration unavailable.
     * </pre>
     *
     * <code>double ticks_per_revolution = 7;</code>
     * @param value The ticksPerRevolution to set.
     * @return This builder for chaining.
     */
    public Builder setTicksPerRevolution(double value) {
      copyOnWrite();
      instance.setTicksPerRevolution(value);
      return this;
    }
    /**
     * <pre>
     * Zero means calibration unavailable.
     * </pre>
     *
     * <code>double ticks_per_revolution = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicksPerRevolution() {
      copyOnWrite();
      instance.clearTicksPerRevolution();
      return this;
    }

    /**
     * <code>uint64 started_robot_ns = 8;</code>
     * @return The startedRobotNs.
     */
    @java.lang.Override
    public long getStartedRobotNs() {
      return instance.getStartedRobotNs();
    }
    /**
     * <code>uint64 started_robot_ns = 8;</code>
     * @param value The startedRobotNs to set.
     * @return This builder for chaining.
     */
    public Builder setStartedRobotNs(long value) {
      copyOnWrite();
      instance.setStartedRobotNs(value);
      return this;
    }
    /**
     * <code>uint64 started_robot_ns = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedRobotNs() {
      copyOnWrite();
      instance.clearStartedRobotNs();
      return this;
    }

    /**
     * <code>double max_power = 9;</code>
     * @return The maxPower.
     */
    @java.lang.Override
    public double getMaxPower() {
      return instance.getMaxPower();
    }
    /**
     * <code>double max_power = 9;</code>
     * @param value The maxPower to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPower(double value) {
      copyOnWrite();
      instance.setMaxPower(value);
      return this;
    }
    /**
     * <code>double max_power = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPower() {
      copyOnWrite();
      instance.clearMaxPower();
      return this;
    }

    /**
     * <code>double current_limit_amps = 10;</code>
     * @return The currentLimitAmps.
     */
    @java.lang.Override
    public double getCurrentLimitAmps() {
      return instance.getCurrentLimitAmps();
    }
    /**
     * <code>double current_limit_amps = 10;</code>
     * @param value The currentLimitAmps to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentLimitAmps(double value) {
      copyOnWrite();
      instance.setCurrentLimitAmps(value);
      return this;
    }
    /**
     * <code>double current_limit_amps = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentLimitAmps() {
      copyOnWrite();
      instance.clearCurrentLimitAmps();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugRunHeader)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "runId_",
            "mechanismId_",
            "mechanismLabel_",
            "motorName_",
            "benchmark_",
            "inputs_",
            org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue.class,
            "ticksPerRevolution_",
            "startedRobotNs_",
            "maxPower_",
            "currentLimitAmps_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0001\u0001\n\n\u0000\u0001\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u1009\u0000\u0006\u001b\u0007\u0000\b\u0003\t\u0000\n\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugRunHeader)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader DEFAULT_INSTANCE;
  static {
    DebugRunHeader defaultInstance = new DebugRunHeader();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugRunHeader.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugRunHeader> PARSER;

  public static com.google.protobuf.Parser<DebugRunHeader> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

