// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * <pre>
 * Debugger protocol messages. These use the same length-delimited TCP stream
 * as telemetry. The Driver Station/Robocol path remains authoritative for
 * OpMode lifecycle and emergency stop.
 * </pre>
 *
 * Protobuf type {@code ftc.robotdata.v2.DebugManifest}
 */
public  final class DebugManifest extends
    com.google.protobuf.GeneratedMessageLite<
        DebugManifest, DebugManifest.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugManifest)
    DebugManifestOrBuilder {
  private DebugManifest() {
    registryId_ = "";
    registryLabel_ = "";
    nodes_ = emptyProtobufList();
    activeNodeId_ = "";
  }
  public static final int REVISION_FIELD_NUMBER = 1;
  private int revision_;
  /**
   * <code>uint32 revision = 1;</code>
   * @return The revision.
   */
  @java.lang.Override
  public int getRevision() {
    return revision_;
  }
  /**
   * <code>uint32 revision = 1;</code>
   * @param value The revision to set.
   */
  private void setRevision(int value) {
    
    revision_ = value;
  }
  /**
   * <code>uint32 revision = 1;</code>
   */
  private void clearRevision() {

    revision_ = 0;
  }

  public static final int REGISTRY_ID_FIELD_NUMBER = 2;
  private java.lang.String registryId_;
  /**
   * <code>string registry_id = 2;</code>
   * @return The registryId.
   */
  @java.lang.Override
  public java.lang.String getRegistryId() {
    return registryId_;
  }
  /**
   * <code>string registry_id = 2;</code>
   * @return The bytes for registryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegistryIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(registryId_);
  }
  /**
   * <code>string registry_id = 2;</code>
   * @param value The registryId to set.
   */
  private void setRegistryId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    registryId_ = value;
  }
  /**
   * <code>string registry_id = 2;</code>
   */
  private void clearRegistryId() {

    registryId_ = getDefaultInstance().getRegistryId();
  }
  /**
   * <code>string registry_id = 2;</code>
   * @param value The bytes for registryId to set.
   */
  private void setRegistryIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    registryId_ = value.toStringUtf8();

  }

  public static final int REGISTRY_LABEL_FIELD_NUMBER = 3;
  private java.lang.String registryLabel_;
  /**
   * <code>string registry_label = 3;</code>
   * @return The registryLabel.
   */
  @java.lang.Override
  public java.lang.String getRegistryLabel() {
    return registryLabel_;
  }
  /**
   * <code>string registry_label = 3;</code>
   * @return The bytes for registryLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegistryLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(registryLabel_);
  }
  /**
   * <code>string registry_label = 3;</code>
   * @param value The registryLabel to set.
   */
  private void setRegistryLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    registryLabel_ = value;
  }
  /**
   * <code>string registry_label = 3;</code>
   */
  private void clearRegistryLabel() {

    registryLabel_ = getDefaultInstance().getRegistryLabel();
  }
  /**
   * <code>string registry_label = 3;</code>
   * @param value The bytes for registryLabel to set.
   */
  private void setRegistryLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    registryLabel_ = value.toStringUtf8();

  }

  public static final int NODES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugNode> nodes_;
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  @java.lang.Override
  public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugNode> getNodesList() {
    return nodes_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  public java.util.List<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugNodeOrBuilder> 
      getNodesOrBuilderList() {
    return nodes_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  @java.lang.Override
  public int getNodesCount() {
    return nodes_.size();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugNode getNodes(int index) {
    return nodes_.get(index);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  public org.firstinspires.ftc.teamcode.data.protocol.DebugNodeOrBuilder getNodesOrBuilder(
      int index) {
    return nodes_.get(index);
  }
  private void ensureNodesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.DebugNode> tmp = nodes_;
    if (!tmp.isModifiable()) {
      nodes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void setNodes(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
    value.getClass();
  ensureNodesIsMutable();
    nodes_.set(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void addNodes(org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
    value.getClass();
  ensureNodesIsMutable();
    nodes_.add(value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void addNodes(
      int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
    value.getClass();
  ensureNodesIsMutable();
    nodes_.add(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void addAllNodes(
      java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugNode> values) {
    ensureNodesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, nodes_);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void clearNodes() {
    nodes_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
   */
  private void removeNodes(int index) {
    ensureNodesIsMutable();
    nodes_.remove(index);
  }

  public static final int ACTIVE_NODE_ID_FIELD_NUMBER = 5;
  private java.lang.String activeNodeId_;
  /**
   * <code>string active_node_id = 5;</code>
   * @return The activeNodeId.
   */
  @java.lang.Override
  public java.lang.String getActiveNodeId() {
    return activeNodeId_;
  }
  /**
   * <code>string active_node_id = 5;</code>
   * @return The bytes for activeNodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActiveNodeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(activeNodeId_);
  }
  /**
   * <code>string active_node_id = 5;</code>
   * @param value The activeNodeId to set.
   */
  private void setActiveNodeId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    activeNodeId_ = value;
  }
  /**
   * <code>string active_node_id = 5;</code>
   */
  private void clearActiveNodeId() {

    activeNodeId_ = getDefaultInstance().getActiveNodeId();
  }
  /**
   * <code>string active_node_id = 5;</code>
   * @param value The bytes for activeNodeId to set.
   */
  private void setActiveNodeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    activeNodeId_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugManifest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Debugger protocol messages. These use the same length-delimited TCP stream
   * as telemetry. The Driver Station/Robocol path remains authoritative for
   * OpMode lifecycle and emergency stop.
   * </pre>
   *
   * Protobuf type {@code ftc.robotdata.v2.DebugManifest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugManifest, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugManifest)
      org.firstinspires.ftc.teamcode.data.protocol.DebugManifestOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugManifest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 revision = 1;</code>
     * @return The revision.
     */
    @java.lang.Override
    public int getRevision() {
      return instance.getRevision();
    }
    /**
     * <code>uint32 revision = 1;</code>
     * @param value The revision to set.
     * @return This builder for chaining.
     */
    public Builder setRevision(int value) {
      copyOnWrite();
      instance.setRevision(value);
      return this;
    }
    /**
     * <code>uint32 revision = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevision() {
      copyOnWrite();
      instance.clearRevision();
      return this;
    }

    /**
     * <code>string registry_id = 2;</code>
     * @return The registryId.
     */
    @java.lang.Override
    public java.lang.String getRegistryId() {
      return instance.getRegistryId();
    }
    /**
     * <code>string registry_id = 2;</code>
     * @return The bytes for registryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegistryIdBytes() {
      return instance.getRegistryIdBytes();
    }
    /**
     * <code>string registry_id = 2;</code>
     * @param value The registryId to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRegistryId(value);
      return this;
    }
    /**
     * <code>string registry_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistryId() {
      copyOnWrite();
      instance.clearRegistryId();
      return this;
    }
    /**
     * <code>string registry_id = 2;</code>
     * @param value The bytes for registryId to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRegistryIdBytes(value);
      return this;
    }

    /**
     * <code>string registry_label = 3;</code>
     * @return The registryLabel.
     */
    @java.lang.Override
    public java.lang.String getRegistryLabel() {
      return instance.getRegistryLabel();
    }
    /**
     * <code>string registry_label = 3;</code>
     * @return The bytes for registryLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRegistryLabelBytes() {
      return instance.getRegistryLabelBytes();
    }
    /**
     * <code>string registry_label = 3;</code>
     * @param value The registryLabel to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setRegistryLabel(value);
      return this;
    }
    /**
     * <code>string registry_label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegistryLabel() {
      copyOnWrite();
      instance.clearRegistryLabel();
      return this;
    }
    /**
     * <code>string registry_label = 3;</code>
     * @param value The bytes for registryLabel to set.
     * @return This builder for chaining.
     */
    public Builder setRegistryLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRegistryLabelBytes(value);
      return this;
    }

    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    @java.lang.Override
    public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugNode> getNodesList() {
      return java.util.Collections.unmodifiableList(
          instance.getNodesList());
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    @java.lang.Override
    public int getNodesCount() {
      return instance.getNodesCount();
    }/**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugNode getNodes(int index) {
      return instance.getNodes(index);
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder setNodes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
      copyOnWrite();
      instance.setNodes(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder setNodes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode.Builder builderForValue) {
      copyOnWrite();
      instance.setNodes(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder addNodes(org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
      copyOnWrite();
      instance.addNodes(value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder addNodes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode value) {
      copyOnWrite();
      instance.addNodes(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder addNodes(
        org.firstinspires.ftc.teamcode.data.protocol.DebugNode.Builder builderForValue) {
      copyOnWrite();
      instance.addNodes(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder addNodes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.DebugNode.Builder builderForValue) {
      copyOnWrite();
      instance.addNodes(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder addAllNodes(
        java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.DebugNode> values) {
      copyOnWrite();
      instance.addAllNodes(values);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder clearNodes() {
      copyOnWrite();
      instance.clearNodes();
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.DebugNode nodes = 4;</code>
     */
    public Builder removeNodes(int index) {
      copyOnWrite();
      instance.removeNodes(index);
      return this;
    }

    /**
     * <code>string active_node_id = 5;</code>
     * @return The activeNodeId.
     */
    @java.lang.Override
    public java.lang.String getActiveNodeId() {
      return instance.getActiveNodeId();
    }
    /**
     * <code>string active_node_id = 5;</code>
     * @return The bytes for activeNodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActiveNodeIdBytes() {
      return instance.getActiveNodeIdBytes();
    }
    /**
     * <code>string active_node_id = 5;</code>
     * @param value The activeNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setActiveNodeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setActiveNodeId(value);
      return this;
    }
    /**
     * <code>string active_node_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearActiveNodeId() {
      copyOnWrite();
      instance.clearActiveNodeId();
      return this;
    }
    /**
     * <code>string active_node_id = 5;</code>
     * @param value The bytes for activeNodeId to set.
     * @return This builder for chaining.
     */
    public Builder setActiveNodeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActiveNodeIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugManifest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugManifest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "revision_",
            "registryId_",
            "registryLabel_",
            "nodes_",
            org.firstinspires.ftc.teamcode.data.protocol.DebugNode.class,
            "activeNodeId_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u000b\u0002\u0208" +
              "\u0003\u0208\u0004\u001b\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugManifest> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugManifest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugManifest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugManifest)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugManifest DEFAULT_INSTANCE;
  static {
    DebugManifest defaultInstance = new DebugManifest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugManifest.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugManifest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugManifest> PARSER;

  public static com.google.protobuf.Parser<DebugManifest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

