// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface DebugCommandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.DebugCommandRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string tool_instance_id = 3;</code>
   * @return The toolInstanceId.
   */
  java.lang.String getToolInstanceId();
  /**
   * <code>string tool_instance_id = 3;</code>
   * @return The bytes for toolInstanceId.
   */
  com.google.protobuf.ByteString
      getToolInstanceIdBytes();

  /**
   * <code>string command_id = 4;</code>
   * @return The commandId.
   */
  java.lang.String getCommandId();
  /**
   * <code>string command_id = 4;</code>
   * @return The bytes for commandId.
   */
  com.google.protobuf.ByteString
      getCommandIdBytes();

  /**
   * <code>uint32 ttl_ms = 5;</code>
   * @return The ttlMs.
   */
  int getTtlMs();

  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue arguments = 6;</code>
   */
  java.util.List<org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue> 
      getArgumentsList();
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue arguments = 6;</code>
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugCommandArgumentValue getArguments(int index);
  /**
   * <code>repeated .ftc.robotdata.v2.DebugCommandArgumentValue arguments = 6;</code>
   */
  int getArgumentsCount();
}
