// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugNode}
 */
public  final class DebugNode extends
    com.google.protobuf.GeneratedMessageLite<
        DebugNode, DebugNode.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugNode)
    DebugNodeOrBuilder {
  private DebugNode() {
    id_ = "";
    parentId_ = "";
    label_ = "";
    description_ = "";
    opModeLabel_ = "";
    disabledReason_ = "";
    parameterIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    commandIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 1;</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int PARENT_ID_FIELD_NUMBER = 2;
  private java.lang.String parentId_;
  /**
   * <code>string parent_id = 2;</code>
   * @return The parentId.
   */
  @java.lang.Override
  public java.lang.String getParentId() {
    return parentId_;
  }
  /**
   * <code>string parent_id = 2;</code>
   * @return The bytes for parentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(parentId_);
  }
  /**
   * <code>string parent_id = 2;</code>
   * @param value The parentId to set.
   */
  private void setParentId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    parentId_ = value;
  }
  /**
   * <code>string parent_id = 2;</code>
   */
  private void clearParentId() {

    parentId_ = getDefaultInstance().getParentId();
  }
  /**
   * <code>string parent_id = 2;</code>
   * @param value The bytes for parentId to set.
   */
  private void setParentIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    parentId_ = value.toStringUtf8();

  }

  public static final int LABEL_FIELD_NUMBER = 3;
  private java.lang.String label_;
  /**
   * <code>string label = 3;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    return label_;
  }
  /**
   * <code>string label = 3;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(label_);
  }
  /**
   * <code>string label = 3;</code>
   * @param value The label to set.
   */
  private void setLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    label_ = value;
  }
  /**
   * <code>string label = 3;</code>
   */
  private void clearLabel() {

    label_ = getDefaultInstance().getLabel();
  }
  /**
   * <code>string label = 3;</code>
   * @param value The bytes for label to set.
   */
  private void setLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    label_ = value.toStringUtf8();

  }

  public static final int DESCRIPTION_FIELD_NUMBER = 4;
  private java.lang.String description_;
  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 4;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 4;</code>
   */
  private void clearDescription() {

    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 4;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();

  }

  public static final int KIND_FIELD_NUMBER = 5;
  private int kind_;
  /**
   * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
   * @return The kind.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind getKind() {
    org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind result = org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind.forNumber(kind_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
   * @param value The kind to set.
   */
  private void setKind(org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static final int SORT_ORDER_FIELD_NUMBER = 6;
  private int sortOrder_;
  /**
   * <code>uint32 sort_order = 6;</code>
   * @return The sortOrder.
   */
  @java.lang.Override
  public int getSortOrder() {
    return sortOrder_;
  }
  /**
   * <code>uint32 sort_order = 6;</code>
   * @param value The sortOrder to set.
   */
  private void setSortOrder(int value) {
    
    sortOrder_ = value;
  }
  /**
   * <code>uint32 sort_order = 6;</code>
   */
  private void clearSortOrder() {

    sortOrder_ = 0;
  }

  public static final int RISK_CLASS_FIELD_NUMBER = 7;
  private int riskClass_;
  /**
   * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
   * @return The enum numeric value on the wire for riskClass.
   */
  @java.lang.Override
  public int getRiskClassValue() {
    return riskClass_;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
   * @return The riskClass.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass getRiskClass() {
    org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass result = org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass.forNumber(riskClass_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
   * @param value The enum numeric value on the wire for riskClass to set.
   */
  private void setRiskClassValue(int value) {
      riskClass_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
   * @param value The riskClass to set.
   */
  private void setRiskClass(org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass value) {
    riskClass_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
   */
  private void clearRiskClass() {

    riskClass_ = 0;
  }

  public static final int OP_MODE_LABEL_FIELD_NUMBER = 8;
  private java.lang.String opModeLabel_;
  /**
   * <code>string op_mode_label = 8;</code>
   * @return The opModeLabel.
   */
  @java.lang.Override
  public java.lang.String getOpModeLabel() {
    return opModeLabel_;
  }
  /**
   * <code>string op_mode_label = 8;</code>
   * @return The bytes for opModeLabel.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOpModeLabelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(opModeLabel_);
  }
  /**
   * <code>string op_mode_label = 8;</code>
   * @param value The opModeLabel to set.
   */
  private void setOpModeLabel(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    opModeLabel_ = value;
  }
  /**
   * <code>string op_mode_label = 8;</code>
   */
  private void clearOpModeLabel() {

    opModeLabel_ = getDefaultInstance().getOpModeLabel();
  }
  /**
   * <code>string op_mode_label = 8;</code>
   * @param value The bytes for opModeLabel to set.
   */
  private void setOpModeLabelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    opModeLabel_ = value.toStringUtf8();

  }

  public static final int SELECTABLE_FIELD_NUMBER = 9;
  private boolean selectable_;
  /**
   * <code>bool selectable = 9;</code>
   * @return The selectable.
   */
  @java.lang.Override
  public boolean getSelectable() {
    return selectable_;
  }
  /**
   * <code>bool selectable = 9;</code>
   * @param value The selectable to set.
   */
  private void setSelectable(boolean value) {
    
    selectable_ = value;
  }
  /**
   * <code>bool selectable = 9;</code>
   */
  private void clearSelectable() {

    selectable_ = false;
  }

  public static final int ENABLED_FIELD_NUMBER = 10;
  private boolean enabled_;
  /**
   * <code>bool enabled = 10;</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }
  /**
   * <code>bool enabled = 10;</code>
   * @param value The enabled to set.
   */
  private void setEnabled(boolean value) {
    
    enabled_ = value;
  }
  /**
   * <code>bool enabled = 10;</code>
   */
  private void clearEnabled() {

    enabled_ = false;
  }

  public static final int DISABLED_REASON_FIELD_NUMBER = 11;
  private java.lang.String disabledReason_;
  /**
   * <code>string disabled_reason = 11;</code>
   * @return The disabledReason.
   */
  @java.lang.Override
  public java.lang.String getDisabledReason() {
    return disabledReason_;
  }
  /**
   * <code>string disabled_reason = 11;</code>
   * @return The bytes for disabledReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisabledReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(disabledReason_);
  }
  /**
   * <code>string disabled_reason = 11;</code>
   * @param value The disabledReason to set.
   */
  private void setDisabledReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    disabledReason_ = value;
  }
  /**
   * <code>string disabled_reason = 11;</code>
   */
  private void clearDisabledReason() {

    disabledReason_ = getDefaultInstance().getDisabledReason();
  }
  /**
   * <code>string disabled_reason = 11;</code>
   * @param value The bytes for disabledReason to set.
   */
  private void setDisabledReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    disabledReason_ = value.toStringUtf8();

  }

  public static final int MAX_OUTPUT_FIELD_NUMBER = 12;
  private double maxOutput_;
  /**
   * <code>double max_output = 12;</code>
   * @return The maxOutput.
   */
  @java.lang.Override
  public double getMaxOutput() {
    return maxOutput_;
  }
  /**
   * <code>double max_output = 12;</code>
   * @param value The maxOutput to set.
   */
  private void setMaxOutput(double value) {
    
    maxOutput_ = value;
  }
  /**
   * <code>double max_output = 12;</code>
   */
  private void clearMaxOutput() {

    maxOutput_ = 0D;
  }

  public static final int MAX_ACTIVE_DURATION_MS_FIELD_NUMBER = 13;
  private int maxActiveDurationMs_;
  /**
   * <code>uint32 max_active_duration_ms = 13;</code>
   * @return The maxActiveDurationMs.
   */
  @java.lang.Override
  public int getMaxActiveDurationMs() {
    return maxActiveDurationMs_;
  }
  /**
   * <code>uint32 max_active_duration_ms = 13;</code>
   * @param value The maxActiveDurationMs to set.
   */
  private void setMaxActiveDurationMs(int value) {
    
    maxActiveDurationMs_ = value;
  }
  /**
   * <code>uint32 max_active_duration_ms = 13;</code>
   */
  private void clearMaxActiveDurationMs() {

    maxActiveDurationMs_ = 0;
  }

  public static final int PARAMETER_IDS_FIELD_NUMBER = 14;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> parameterIds_;
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @return A list containing the parameterIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getParameterIdsList() {
    return parameterIds_;
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @return The count of parameterIds.
   */
  @java.lang.Override
  public int getParameterIdsCount() {
    return parameterIds_.size();
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param index The index of the element to return.
   * @return The parameterIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getParameterIds(int index) {
    return parameterIds_.get(index);
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param index The index of the value to return.
   * @return The bytes of the parameterIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParameterIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        parameterIds_.get(index));
  }
  private void ensureParameterIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        parameterIds_;  if (!tmp.isModifiable()) {
      parameterIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param index The index to set the value at.
   * @param value The parameterIds to set.
   */
  private void setParameterIds(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureParameterIdsIsMutable();
    parameterIds_.set(index, value);
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param value The parameterIds to add.
   */
  private void addParameterIds(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureParameterIdsIsMutable();
    parameterIds_.add(value);
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param values The parameterIds to add.
   */
  private void addAllParameterIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureParameterIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, parameterIds_);
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   */
  private void clearParameterIds() {
    parameterIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string parameter_ids = 14;</code>
   * @param value The bytes of the parameterIds to add.
   */
  private void addParameterIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureParameterIdsIsMutable();
    parameterIds_.add(value.toStringUtf8());
  }

  public static final int COMMAND_IDS_FIELD_NUMBER = 15;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> commandIds_;
  /**
   * <code>repeated string command_ids = 15;</code>
   * @return A list containing the commandIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getCommandIdsList() {
    return commandIds_;
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @return The count of commandIds.
   */
  @java.lang.Override
  public int getCommandIdsCount() {
    return commandIds_.size();
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param index The index of the element to return.
   * @return The commandIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getCommandIds(int index) {
    return commandIds_.get(index);
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param index The index of the value to return.
   * @return The bytes of the commandIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommandIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        commandIds_.get(index));
  }
  private void ensureCommandIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        commandIds_;  if (!tmp.isModifiable()) {
      commandIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param index The index to set the value at.
   * @param value The commandIds to set.
   */
  private void setCommandIds(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCommandIdsIsMutable();
    commandIds_.set(index, value);
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param value The commandIds to add.
   */
  private void addCommandIds(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCommandIdsIsMutable();
    commandIds_.add(value);
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param values The commandIds to add.
   */
  private void addAllCommandIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureCommandIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, commandIds_);
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   */
  private void clearCommandIds() {
    commandIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string command_ids = 15;</code>
   * @param value The bytes of the commandIds to add.
   */
  private void addCommandIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureCommandIdsIsMutable();
    commandIds_.add(value.toStringUtf8());
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugNode prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugNode, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugNode)
      org.firstinspires.ftc.teamcode.data.protocol.DebugNodeOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugNode.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string parent_id = 2;</code>
     * @return The parentId.
     */
    @java.lang.Override
    public java.lang.String getParentId() {
      return instance.getParentId();
    }
    /**
     * <code>string parent_id = 2;</code>
     * @return The bytes for parentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParentIdBytes() {
      return instance.getParentIdBytes();
    }
    /**
     * <code>string parent_id = 2;</code>
     * @param value The parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentId(
        java.lang.String value) {
      copyOnWrite();
      instance.setParentId(value);
      return this;
    }
    /**
     * <code>string parent_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentId() {
      copyOnWrite();
      instance.clearParentId();
      return this;
    }
    /**
     * <code>string parent_id = 2;</code>
     * @param value The bytes for parentId to set.
     * @return This builder for chaining.
     */
    public Builder setParentIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setParentIdBytes(value);
      return this;
    }

    /**
     * <code>string label = 3;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      return instance.getLabel();
    }
    /**
     * <code>string label = 3;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      return instance.getLabelBytes();
    }
    /**
     * <code>string label = 3;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setLabel(value);
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      copyOnWrite();
      instance.clearLabel();
      return this;
    }
    /**
     * <code>string label = 3;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLabelBytes(value);
      return this;
    }

    /**
     * <code>string description = 4;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 4;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 4;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 4;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
     * @return The kind.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(org.firstinspires.ftc.teamcode.data.protocol.DebugNodeKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugNodeKind kind = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <code>uint32 sort_order = 6;</code>
     * @return The sortOrder.
     */
    @java.lang.Override
    public int getSortOrder() {
      return instance.getSortOrder();
    }
    /**
     * <code>uint32 sort_order = 6;</code>
     * @param value The sortOrder to set.
     * @return This builder for chaining.
     */
    public Builder setSortOrder(int value) {
      copyOnWrite();
      instance.setSortOrder(value);
      return this;
    }
    /**
     * <code>uint32 sort_order = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSortOrder() {
      copyOnWrite();
      instance.clearSortOrder();
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
     * @return The enum numeric value on the wire for riskClass.
     */
    @java.lang.Override
    public int getRiskClassValue() {
      return instance.getRiskClassValue();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
     * @param value The riskClass to set.
     * @return This builder for chaining.
     */
    public Builder setRiskClassValue(int value) {
      copyOnWrite();
      instance.setRiskClassValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
     * @return The riskClass.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass getRiskClass() {
      return instance.getRiskClass();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
     * @param value The enum numeric value on the wire for riskClass to set.
     * @return This builder for chaining.
     */
    public Builder setRiskClass(org.firstinspires.ftc.teamcode.data.protocol.DebugRiskClass value) {
      copyOnWrite();
      instance.setRiskClass(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugRiskClass risk_class = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearRiskClass() {
      copyOnWrite();
      instance.clearRiskClass();
      return this;
    }

    /**
     * <code>string op_mode_label = 8;</code>
     * @return The opModeLabel.
     */
    @java.lang.Override
    public java.lang.String getOpModeLabel() {
      return instance.getOpModeLabel();
    }
    /**
     * <code>string op_mode_label = 8;</code>
     * @return The bytes for opModeLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOpModeLabelBytes() {
      return instance.getOpModeLabelBytes();
    }
    /**
     * <code>string op_mode_label = 8;</code>
     * @param value The opModeLabel to set.
     * @return This builder for chaining.
     */
    public Builder setOpModeLabel(
        java.lang.String value) {
      copyOnWrite();
      instance.setOpModeLabel(value);
      return this;
    }
    /**
     * <code>string op_mode_label = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOpModeLabel() {
      copyOnWrite();
      instance.clearOpModeLabel();
      return this;
    }
    /**
     * <code>string op_mode_label = 8;</code>
     * @param value The bytes for opModeLabel to set.
     * @return This builder for chaining.
     */
    public Builder setOpModeLabelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOpModeLabelBytes(value);
      return this;
    }

    /**
     * <code>bool selectable = 9;</code>
     * @return The selectable.
     */
    @java.lang.Override
    public boolean getSelectable() {
      return instance.getSelectable();
    }
    /**
     * <code>bool selectable = 9;</code>
     * @param value The selectable to set.
     * @return This builder for chaining.
     */
    public Builder setSelectable(boolean value) {
      copyOnWrite();
      instance.setSelectable(value);
      return this;
    }
    /**
     * <code>bool selectable = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSelectable() {
      copyOnWrite();
      instance.clearSelectable();
      return this;
    }

    /**
     * <code>bool enabled = 10;</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return instance.getEnabled();
    }
    /**
     * <code>bool enabled = 10;</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {
      copyOnWrite();
      instance.setEnabled(value);
      return this;
    }
    /**
     * <code>bool enabled = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      copyOnWrite();
      instance.clearEnabled();
      return this;
    }

    /**
     * <code>string disabled_reason = 11;</code>
     * @return The disabledReason.
     */
    @java.lang.Override
    public java.lang.String getDisabledReason() {
      return instance.getDisabledReason();
    }
    /**
     * <code>string disabled_reason = 11;</code>
     * @return The bytes for disabledReason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisabledReasonBytes() {
      return instance.getDisabledReasonBytes();
    }
    /**
     * <code>string disabled_reason = 11;</code>
     * @param value The disabledReason to set.
     * @return This builder for chaining.
     */
    public Builder setDisabledReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisabledReason(value);
      return this;
    }
    /**
     * <code>string disabled_reason = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisabledReason() {
      copyOnWrite();
      instance.clearDisabledReason();
      return this;
    }
    /**
     * <code>string disabled_reason = 11;</code>
     * @param value The bytes for disabledReason to set.
     * @return This builder for chaining.
     */
    public Builder setDisabledReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisabledReasonBytes(value);
      return this;
    }

    /**
     * <code>double max_output = 12;</code>
     * @return The maxOutput.
     */
    @java.lang.Override
    public double getMaxOutput() {
      return instance.getMaxOutput();
    }
    /**
     * <code>double max_output = 12;</code>
     * @param value The maxOutput to set.
     * @return This builder for chaining.
     */
    public Builder setMaxOutput(double value) {
      copyOnWrite();
      instance.setMaxOutput(value);
      return this;
    }
    /**
     * <code>double max_output = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxOutput() {
      copyOnWrite();
      instance.clearMaxOutput();
      return this;
    }

    /**
     * <code>uint32 max_active_duration_ms = 13;</code>
     * @return The maxActiveDurationMs.
     */
    @java.lang.Override
    public int getMaxActiveDurationMs() {
      return instance.getMaxActiveDurationMs();
    }
    /**
     * <code>uint32 max_active_duration_ms = 13;</code>
     * @param value The maxActiveDurationMs to set.
     * @return This builder for chaining.
     */
    public Builder setMaxActiveDurationMs(int value) {
      copyOnWrite();
      instance.setMaxActiveDurationMs(value);
      return this;
    }
    /**
     * <code>uint32 max_active_duration_ms = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxActiveDurationMs() {
      copyOnWrite();
      instance.clearMaxActiveDurationMs();
      return this;
    }

    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @return A list containing the parameterIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getParameterIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getParameterIdsList());
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @return The count of parameterIds.
     */
    @java.lang.Override
    public int getParameterIdsCount() {
      return instance.getParameterIdsCount();
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param index The index of the element to return.
     * @return The parameterIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getParameterIds(int index) {
      return instance.getParameterIds(index);
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param index The index of the value to return.
     * @return The bytes of the parameterIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParameterIdsBytes(int index) {
      return instance.getParameterIdsBytes(index);
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param index The index to set the value at.
     * @param value The parameterIds to set.
     * @return This builder for chaining.
     */
    public Builder setParameterIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setParameterIds(index, value);
      return this;
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param value The parameterIds to add.
     * @return This builder for chaining.
     */
    public Builder addParameterIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addParameterIds(value);
      return this;
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param values The parameterIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllParameterIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllParameterIds(values);
      return this;
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameterIds() {
      copyOnWrite();
      instance.clearParameterIds();
      return this;
    }
    /**
     * <code>repeated string parameter_ids = 14;</code>
     * @param value The bytes of the parameterIds to add.
     * @return This builder for chaining.
     */
    public Builder addParameterIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addParameterIdsBytes(value);
      return this;
    }

    /**
     * <code>repeated string command_ids = 15;</code>
     * @return A list containing the commandIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getCommandIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCommandIdsList());
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @return The count of commandIds.
     */
    @java.lang.Override
    public int getCommandIdsCount() {
      return instance.getCommandIdsCount();
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param index The index of the element to return.
     * @return The commandIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getCommandIds(int index) {
      return instance.getCommandIds(index);
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param index The index of the value to return.
     * @return The bytes of the commandIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCommandIdsBytes(int index) {
      return instance.getCommandIdsBytes(index);
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param index The index to set the value at.
     * @param value The commandIds to set.
     * @return This builder for chaining.
     */
    public Builder setCommandIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setCommandIds(index, value);
      return this;
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param value The commandIds to add.
     * @return This builder for chaining.
     */
    public Builder addCommandIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addCommandIds(value);
      return this;
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param values The commandIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllCommandIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllCommandIds(values);
      return this;
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandIds() {
      copyOnWrite();
      instance.clearCommandIds();
      return this;
    }
    /**
     * <code>repeated string command_ids = 15;</code>
     * @param value The bytes of the commandIds to add.
     * @return This builder for chaining.
     */
    public Builder addCommandIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addCommandIdsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugNode)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugNode();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "parentId_",
            "label_",
            "description_",
            "kind_",
            "sortOrder_",
            "riskClass_",
            "opModeLabel_",
            "selectable_",
            "enabled_",
            "disabledReason_",
            "maxOutput_",
            "maxActiveDurationMs_",
            "parameterIds_",
            "commandIds_",
          };
          java.lang.String info =
              "\u0000\u000f\u0000\u0000\u0001\u000f\u000f\u0000\u0002\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\f\u0006\u000b\u0007\f\b\u0208\t\u0007\n\u0007\u000b" +
              "\u0208\f\u0000\r\u000b\u000e\u021a\u000f\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugNode> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugNode.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugNode>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugNode)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugNode DEFAULT_INSTANCE;
  static {
    DebugNode defaultInstance = new DebugNode();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugNode.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugNode> PARSER;

  public static com.google.protobuf.Parser<DebugNode> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

