// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf enum {@code ftc.robotdata.v2.DebugSessionState}
 */
public enum DebugSessionState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>DEBUG_SESSION_STATE_UNSPECIFIED = 0;</code>
   */
  DEBUG_SESSION_STATE_UNSPECIFIED(0),
  /**
   * <code>DEBUG_IDLE = 1;</code>
   */
  DEBUG_IDLE(1),
  /**
   * <code>DEBUG_SELECTED = 2;</code>
   */
  DEBUG_SELECTED(2),
  /**
   * <code>DEBUG_READY = 3;</code>
   */
  DEBUG_READY(3),
  /**
   * <code>DEBUG_RUNNING = 4;</code>
   */
  DEBUG_RUNNING(4),
  /**
   * <code>DEBUG_STOPPING = 5;</code>
   */
  DEBUG_STOPPING(5),
  /**
   * <code>DEBUG_FAULTED = 6;</code>
   */
  DEBUG_FAULTED(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DEBUG_SESSION_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int DEBUG_SESSION_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEBUG_IDLE = 1;</code>
   */
  public static final int DEBUG_IDLE_VALUE = 1;
  /**
   * <code>DEBUG_SELECTED = 2;</code>
   */
  public static final int DEBUG_SELECTED_VALUE = 2;
  /**
   * <code>DEBUG_READY = 3;</code>
   */
  public static final int DEBUG_READY_VALUE = 3;
  /**
   * <code>DEBUG_RUNNING = 4;</code>
   */
  public static final int DEBUG_RUNNING_VALUE = 4;
  /**
   * <code>DEBUG_STOPPING = 5;</code>
   */
  public static final int DEBUG_STOPPING_VALUE = 5;
  /**
   * <code>DEBUG_FAULTED = 6;</code>
   */
  public static final int DEBUG_FAULTED_VALUE = 6;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DebugSessionState valueOf(int value) {
    return forNumber(value);
  }

  public static DebugSessionState forNumber(int value) {
    switch (value) {
      case 0: return DEBUG_SESSION_STATE_UNSPECIFIED;
      case 1: return DEBUG_IDLE;
      case 2: return DEBUG_SELECTED;
      case 3: return DEBUG_READY;
      case 4: return DEBUG_RUNNING;
      case 5: return DEBUG_STOPPING;
      case 6: return DEBUG_FAULTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DebugSessionState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DebugSessionState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DebugSessionState>() {
          @java.lang.Override
          public DebugSessionState findValueByNumber(int number) {
            return DebugSessionState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return DebugSessionStateVerifier.INSTANCE;
  }

  private static final class DebugSessionStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new DebugSessionStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return DebugSessionState.forNumber(number) != null;
          }
        };

  private final int value;

  private DebugSessionState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ftc.robotdata.v2.DebugSessionState)
}

