// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.DebugSelectResponse}
 */
public  final class DebugSelectResponse extends
    com.google.protobuf.GeneratedMessageLite<
        DebugSelectResponse, DebugSelectResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.DebugSelectResponse)
    DebugSelectResponseOrBuilder {
  private DebugSelectResponse() {
    requestId_ = "";
    nodeId_ = "";
    rejectionCode_ = "";
    message_ = "";
  }
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private java.lang.String requestId_;
  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public java.lang.String getRequestId() {
    return requestId_;
  }
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(requestId_);
  }
  /**
   * <code>string request_id = 1;</code>
   * @param value The requestId to set.
   */
  private void setRequestId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    requestId_ = value;
  }
  /**
   * <code>string request_id = 1;</code>
   */
  private void clearRequestId() {

    requestId_ = getDefaultInstance().getRequestId();
  }
  /**
   * <code>string request_id = 1;</code>
   * @param value The bytes for requestId to set.
   */
  private void setRequestIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    requestId_ = value.toStringUtf8();

  }

  public static final int ACCEPTED_FIELD_NUMBER = 2;
  private boolean accepted_;
  /**
   * <code>bool accepted = 2;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }
  /**
   * <code>bool accepted = 2;</code>
   * @param value The accepted to set.
   */
  private void setAccepted(boolean value) {
    
    accepted_ = value;
  }
  /**
   * <code>bool accepted = 2;</code>
   */
  private void clearAccepted() {

    accepted_ = false;
  }

  public static final int NODE_ID_FIELD_NUMBER = 3;
  private java.lang.String nodeId_;
  /**
   * <code>string node_id = 3;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    return nodeId_;
  }
  /**
   * <code>string node_id = 3;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nodeId_);
  }
  /**
   * <code>string node_id = 3;</code>
   * @param value The nodeId to set.
   */
  private void setNodeId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nodeId_ = value;
  }
  /**
   * <code>string node_id = 3;</code>
   */
  private void clearNodeId() {

    nodeId_ = getDefaultInstance().getNodeId();
  }
  /**
   * <code>string node_id = 3;</code>
   * @param value The bytes for nodeId to set.
   */
  private void setNodeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nodeId_ = value.toStringUtf8();

  }

  public static final int STATE_FIELD_NUMBER = 4;
  private int state_;
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override
  public int getStateValue() {
    return state_;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
   * @return The state.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState getState() {
    org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState result = org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState.forNumber(state_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
   * @param value The enum numeric value on the wire for state to set.
   */
  private void setStateValue(int value) {
      state_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
   * @param value The state to set.
   */
  private void setState(org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState value) {
    state_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int REJECTION_CODE_FIELD_NUMBER = 5;
  private java.lang.String rejectionCode_;
  /**
   * <code>string rejection_code = 5;</code>
   * @return The rejectionCode.
   */
  @java.lang.Override
  public java.lang.String getRejectionCode() {
    return rejectionCode_;
  }
  /**
   * <code>string rejection_code = 5;</code>
   * @return The bytes for rejectionCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRejectionCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(rejectionCode_);
  }
  /**
   * <code>string rejection_code = 5;</code>
   * @param value The rejectionCode to set.
   */
  private void setRejectionCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    rejectionCode_ = value;
  }
  /**
   * <code>string rejection_code = 5;</code>
   */
  private void clearRejectionCode() {

    rejectionCode_ = getDefaultInstance().getRejectionCode();
  }
  /**
   * <code>string rejection_code = 5;</code>
   * @param value The bytes for rejectionCode to set.
   */
  private void setRejectionCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    rejectionCode_ = value.toStringUtf8();

  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private java.lang.String message_;
  /**
   * <code>string message = 6;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    return message_;
  }
  /**
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(message_);
  }
  /**
   * <code>string message = 6;</code>
   * @param value The message to set.
   */
  private void setMessage(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    message_ = value;
  }
  /**
   * <code>string message = 6;</code>
   */
  private void clearMessage() {

    message_ = getDefaultInstance().getMessage();
  }
  /**
   * <code>string message = 6;</code>
   * @param value The bytes for message to set.
   */
  private void setMessageBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    message_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.DebugSelectResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.DebugSelectResponse)
      org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponseOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      return instance.getRequestId();
    }
    /**
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      return instance.getRequestIdBytes();
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRequestId(value);
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      copyOnWrite();
      instance.clearRequestId();
      return this;
    }
    /**
     * <code>string request_id = 1;</code>
     * @param value The bytes for requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRequestIdBytes(value);
      return this;
    }

    /**
     * <code>bool accepted = 2;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return instance.getAccepted();
    }
    /**
     * <code>bool accepted = 2;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {
      copyOnWrite();
      instance.setAccepted(value);
      return this;
    }
    /**
     * <code>bool accepted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      copyOnWrite();
      instance.clearAccepted();
      return this;
    }

    /**
     * <code>string node_id = 3;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      return instance.getNodeId();
    }
    /**
     * <code>string node_id = 3;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      return instance.getNodeIdBytes();
    }
    /**
     * <code>string node_id = 3;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNodeId(value);
      return this;
    }
    /**
     * <code>string node_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      copyOnWrite();
      instance.clearNodeId();
      return this;
    }
    /**
     * <code>string node_id = 3;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNodeIdBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override
    public int getStateValue() {
      return instance.getStateValue();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      copyOnWrite();
      instance.setStateValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
     * @return The state.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState getState() {
      return instance.getState();
    }
    /**
     * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setState(org.firstinspires.ftc.teamcode.data.protocol.DebugSessionState value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.DebugSessionState state = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <code>string rejection_code = 5;</code>
     * @return The rejectionCode.
     */
    @java.lang.Override
    public java.lang.String getRejectionCode() {
      return instance.getRejectionCode();
    }
    /**
     * <code>string rejection_code = 5;</code>
     * @return The bytes for rejectionCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRejectionCodeBytes() {
      return instance.getRejectionCodeBytes();
    }
    /**
     * <code>string rejection_code = 5;</code>
     * @param value The rejectionCode to set.
     * @return This builder for chaining.
     */
    public Builder setRejectionCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setRejectionCode(value);
      return this;
    }
    /**
     * <code>string rejection_code = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRejectionCode() {
      copyOnWrite();
      instance.clearRejectionCode();
      return this;
    }
    /**
     * <code>string rejection_code = 5;</code>
     * @param value The bytes for rejectionCode to set.
     * @return This builder for chaining.
     */
    public Builder setRejectionCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRejectionCodeBytes(value);
      return this;
    }

    /**
     * <code>string message = 6;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>string message = 6;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return instance.getMessageBytes();
    }
    /**
     * <code>string message = 6;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }
    /**
     * <code>string message = 6;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.DebugSelectResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "requestId_",
            "accepted_",
            "nodeId_",
            "state_",
            "rejectionCode_",
            "message_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
              "\u0003\u0208\u0004\f\u0005\u0208\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.DebugSelectResponse)
  private static final org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse DEFAULT_INSTANCE;
  static {
    DebugSelectResponse defaultInstance = new DebugSelectResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DebugSelectResponse.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DebugSelectResponse> PARSER;

  public static com.google.protobuf.Parser<DebugSelectResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

