// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface DebugParameterSetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.DebugParameterSetRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string tool_instance_id = 3;</code>
   * @return The toolInstanceId.
   */
  java.lang.String getToolInstanceId();
  /**
   * <code>string tool_instance_id = 3;</code>
   * @return The bytes for toolInstanceId.
   */
  com.google.protobuf.ByteString
      getToolInstanceIdBytes();

  /**
   * <code>string parameter_id = 4;</code>
   * @return The parameterId.
   */
  java.lang.String getParameterId();
  /**
   * <code>string parameter_id = 4;</code>
   * @return The bytes for parameterId.
   */
  com.google.protobuf.ByteString
      getParameterIdBytes();

  /**
   * <code>double float64_value = 5;</code>
   * @return The float64Value.
   */
  double getFloat64Value();

  /**
   * <code>uint32 ttl_ms = 6;</code>
   * @return The ttlMs.
   */
  int getTtlMs();
}
