// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface EnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Envelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 protocol_version = 1;</code>
   * @return The protocolVersion.
   */
  int getProtocolVersion();

  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes session_id = 2;</code>
   * @return The sessionId.
   */
  com.google.protobuf.ByteString getSessionId();

  /**
   * <pre>
   * 16-byte RFC 4122 UUID
   * </pre>
   *
   * <code>bytes connection_id = 3;</code>
   * @return The connectionId.
   */
  com.google.protobuf.ByteString getConnectionId();

  /**
   * <code>uint64 connection_sequence = 4;</code>
   * @return The connectionSequence.
   */
  long getConnectionSequence();

  /**
   * <code>uint64 robot_elapsed_ns = 5;</code>
   * @return The robotElapsedNs.
   */
  long getRobotElapsedNs();

  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.ftc.robotdata.v2.Hello hello = 10;</code>
   * @return The hello.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Hello getHello();

  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   * @return Whether the helloAck field is set.
   */
  boolean hasHelloAck();
  /**
   * <code>.ftc.robotdata.v2.HelloAck hello_ack = 11;</code>
   * @return The helloAck.
   */
  org.firstinspires.ftc.teamcode.data.protocol.HelloAck getHelloAck();

  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   * @return Whether the schema field is set.
   */
  boolean hasSchema();
  /**
   * <code>.ftc.robotdata.v2.Schema schema = 12;</code>
   * @return The schema.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Schema getSchema();

  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   * @return Whether the sampleBatch field is set.
   */
  boolean hasSampleBatch();
  /**
   * <code>.ftc.robotdata.v2.SampleBatch sample_batch = 13;</code>
   * @return The sampleBatch.
   */
  org.firstinspires.ftc.teamcode.data.protocol.SampleBatch getSampleBatch();

  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>.ftc.robotdata.v2.Event event = 14;</code>
   * @return The event.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Event getEvent();

  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   * @return Whether the heartbeat field is set.
   */
  boolean hasHeartbeat();
  /**
   * <code>.ftc.robotdata.v2.Heartbeat heartbeat = 15;</code>
   * @return The heartbeat.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Heartbeat getHeartbeat();

  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   * @return Whether the gap field is set.
   */
  boolean hasGap();
  /**
   * <code>.ftc.robotdata.v2.Gap gap = 16;</code>
   * @return The gap.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Gap getGap();

  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   * @return Whether the sessionEnd field is set.
   */
  boolean hasSessionEnd();
  /**
   * <code>.ftc.robotdata.v2.SessionEnd session_end = 17;</code>
   * @return The sessionEnd.
   */
  org.firstinspires.ftc.teamcode.data.protocol.SessionEnd getSessionEnd();

  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   * @return Whether the gamepad field is set.
   */
  boolean hasGamepad();
  /**
   * <code>.ftc.robotdata.v2.GamepadSnapshot gamepad = 18;</code>
   * @return The gamepad.
   */
  org.firstinspires.ftc.teamcode.data.protocol.GamepadSnapshot getGamepad();

  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.ftc.robotdata.v2.ProtocolError error = 19;</code>
   * @return The error.
   */
  org.firstinspires.ftc.teamcode.data.protocol.ProtocolError getError();

  /**
   * <code>.ftc.robotdata.v2.DebugManifest debug_manifest = 20;</code>
   * @return Whether the debugManifest field is set.
   */
  boolean hasDebugManifest();
  /**
   * <code>.ftc.robotdata.v2.DebugManifest debug_manifest = 20;</code>
   * @return The debugManifest.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugManifest getDebugManifest();

  /**
   * <code>.ftc.robotdata.v2.DebugSelectRequest debug_select_request = 21;</code>
   * @return Whether the debugSelectRequest field is set.
   */
  boolean hasDebugSelectRequest();
  /**
   * <code>.ftc.robotdata.v2.DebugSelectRequest debug_select_request = 21;</code>
   * @return The debugSelectRequest.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugSelectRequest getDebugSelectRequest();

  /**
   * <code>.ftc.robotdata.v2.DebugSelectResponse debug_select_response = 22;</code>
   * @return Whether the debugSelectResponse field is set.
   */
  boolean hasDebugSelectResponse();
  /**
   * <code>.ftc.robotdata.v2.DebugSelectResponse debug_select_response = 22;</code>
   * @return The debugSelectResponse.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugSelectResponse getDebugSelectResponse();

  /**
   * <code>.ftc.robotdata.v2.DebugToolReady debug_tool_ready = 23;</code>
   * @return Whether the debugToolReady field is set.
   */
  boolean hasDebugToolReady();
  /**
   * <code>.ftc.robotdata.v2.DebugToolReady debug_tool_ready = 23;</code>
   * @return The debugToolReady.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugToolReady getDebugToolReady();

  /**
   * <code>.ftc.robotdata.v2.DebugToolState debug_tool_state = 24;</code>
   * @return Whether the debugToolState field is set.
   */
  boolean hasDebugToolState();
  /**
   * <code>.ftc.robotdata.v2.DebugToolState debug_tool_state = 24;</code>
   * @return The debugToolState.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugToolState getDebugToolState();

  /**
   * <code>.ftc.robotdata.v2.DebugParameterSetRequest debug_parameter_set_request = 25;</code>
   * @return Whether the debugParameterSetRequest field is set.
   */
  boolean hasDebugParameterSetRequest();
  /**
   * <code>.ftc.robotdata.v2.DebugParameterSetRequest debug_parameter_set_request = 25;</code>
   * @return The debugParameterSetRequest.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugParameterSetRequest getDebugParameterSetRequest();

  /**
   * <code>.ftc.robotdata.v2.DebugParameterSetResponse debug_parameter_set_response = 26;</code>
   * @return Whether the debugParameterSetResponse field is set.
   */
  boolean hasDebugParameterSetResponse();
  /**
   * <code>.ftc.robotdata.v2.DebugParameterSetResponse debug_parameter_set_response = 26;</code>
   * @return The debugParameterSetResponse.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugParameterSetResponse getDebugParameterSetResponse();

  /**
   * <code>.ftc.robotdata.v2.DebugCommandRequest debug_command_request = 27;</code>
   * @return Whether the debugCommandRequest field is set.
   */
  boolean hasDebugCommandRequest();
  /**
   * <code>.ftc.robotdata.v2.DebugCommandRequest debug_command_request = 27;</code>
   * @return The debugCommandRequest.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugCommandRequest getDebugCommandRequest();

  /**
   * <code>.ftc.robotdata.v2.DebugCommandResponse debug_command_response = 28;</code>
   * @return Whether the debugCommandResponse field is set.
   */
  boolean hasDebugCommandResponse();
  /**
   * <code>.ftc.robotdata.v2.DebugCommandResponse debug_command_response = 28;</code>
   * @return The debugCommandResponse.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugCommandResponse getDebugCommandResponse();

  /**
   * <code>.ftc.robotdata.v2.DebugSafetyState debug_safety_state = 29;</code>
   * @return Whether the debugSafetyState field is set.
   */
  boolean hasDebugSafetyState();
  /**
   * <code>.ftc.robotdata.v2.DebugSafetyState debug_safety_state = 29;</code>
   * @return The debugSafetyState.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugSafetyState getDebugSafetyState();

  /**
   * <code>.ftc.robotdata.v2.DebugRunStatus debug_run_status = 30;</code>
   * @return Whether the debugRunStatus field is set.
   */
  boolean hasDebugRunStatus();
  /**
   * <code>.ftc.robotdata.v2.DebugRunStatus debug_run_status = 30;</code>
   * @return The debugRunStatus.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugRunStatus getDebugRunStatus();

  /**
   * <code>.ftc.robotdata.v2.DebugRunHeader debug_run_header = 31;</code>
   * @return Whether the debugRunHeader field is set.
   */
  boolean hasDebugRunHeader();
  /**
   * <code>.ftc.robotdata.v2.DebugRunHeader debug_run_header = 31;</code>
   * @return The debugRunHeader.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugRunHeader getDebugRunHeader();

  /**
   * <code>.ftc.robotdata.v2.DebugRunChunk debug_run_chunk = 32;</code>
   * @return Whether the debugRunChunk field is set.
   */
  boolean hasDebugRunChunk();
  /**
   * <code>.ftc.robotdata.v2.DebugRunChunk debug_run_chunk = 32;</code>
   * @return The debugRunChunk.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugRunChunk getDebugRunChunk();

  /**
   * <code>.ftc.robotdata.v2.DebugRunEnd debug_run_end = 33;</code>
   * @return Whether the debugRunEnd field is set.
   */
  boolean hasDebugRunEnd();
  /**
   * <code>.ftc.robotdata.v2.DebugRunEnd debug_run_end = 33;</code>
   * @return The debugRunEnd.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugRunEnd getDebugRunEnd();

  /**
   * <code>.ftc.robotdata.v2.DebugRunAck debug_run_ack = 34;</code>
   * @return Whether the debugRunAck field is set.
   */
  boolean hasDebugRunAck();
  /**
   * <code>.ftc.robotdata.v2.DebugRunAck debug_run_ack = 34;</code>
   * @return The debugRunAck.
   */
  org.firstinspires.ftc.teamcode.data.protocol.DebugRunAck getDebugRunAck();

  public org.firstinspires.ftc.teamcode.data.protocol.Envelope.BodyCase getBodyCase();
}
