// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.Event}
 */
public  final class Event extends
    com.google.protobuf.GeneratedMessageLite<
        Event, Event.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.Event)
    EventOrBuilder {
  private Event() {
    name_ = "";
    attributes_ = emptyProtobufList();
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int SEVERITY_FIELD_NUMBER = 2;
  private int severity_;
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @return The enum numeric value on the wire for severity.
   */
  @java.lang.Override
  public int getSeverityValue() {
    return severity_;
  }
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @return The severity.
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Severity getSeverity() {
    org.firstinspires.ftc.teamcode.data.protocol.Severity result = org.firstinspires.ftc.teamcode.data.protocol.Severity.forNumber(severity_);
    return result == null ? org.firstinspires.ftc.teamcode.data.protocol.Severity.UNRECOGNIZED : result;
  }
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @param value The enum numeric value on the wire for severity to set.
   */
  private void setSeverityValue(int value) {
      severity_ = value;
  }
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @param value The severity to set.
   */
  private void setSeverity(org.firstinspires.ftc.teamcode.data.protocol.Severity value) {
    severity_ = value.getNumber();

  }
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   */
  private void clearSeverity() {

    severity_ = 0;
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.Attribute> attributes_;
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.Attribute> getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  public java.util.List<? extends org.firstinspires.ftc.teamcode.data.protocol.AttributeOrBuilder> 
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  @java.lang.Override
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  @java.lang.Override
  public org.firstinspires.ftc.teamcode.data.protocol.Attribute getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  public org.firstinspires.ftc.teamcode.data.protocol.AttributeOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }
  private void ensureAttributesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<org.firstinspires.ftc.teamcode.data.protocol.Attribute> tmp = attributes_;
    if (!tmp.isModifiable()) {
      attributes_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void setAttributes(
      int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
    value.getClass();
  ensureAttributesIsMutable();
    attributes_.set(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void addAttributes(org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
    value.getClass();
  ensureAttributesIsMutable();
    attributes_.add(value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void addAttributes(
      int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
    value.getClass();
  ensureAttributesIsMutable();
    attributes_.add(index, value);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void addAllAttributes(
      java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.Attribute> values) {
    ensureAttributesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, attributes_);
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void clearAttributes() {
    attributes_ = emptyProtobufList();
  }
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  private void removeAttributes(int index) {
    ensureAttributesIsMutable();
    attributes_.remove(index);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.Event prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.Event, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.Event)
      org.firstinspires.ftc.teamcode.data.protocol.EventOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.Event.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
     * @return The enum numeric value on the wire for severity.
     */
    @java.lang.Override
    public int getSeverityValue() {
      return instance.getSeverityValue();
    }
    /**
     * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityValue(int value) {
      copyOnWrite();
      instance.setSeverityValue(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
     * @return The severity.
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Severity getSeverity() {
      return instance.getSeverity();
    }
    /**
     * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
     * @param value The enum numeric value on the wire for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(org.firstinspires.ftc.teamcode.data.protocol.Severity value) {
      copyOnWrite();
      instance.setSeverity(value);
      return this;
    }
    /**
     * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      copyOnWrite();
      instance.clearSeverity();
      return this;
    }

    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    @java.lang.Override
    public java.util.List<org.firstinspires.ftc.teamcode.data.protocol.Attribute> getAttributesList() {
      return java.util.Collections.unmodifiableList(
          instance.getAttributesList());
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    @java.lang.Override
    public int getAttributesCount() {
      return instance.getAttributesCount();
    }/**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    @java.lang.Override
    public org.firstinspires.ftc.teamcode.data.protocol.Attribute getAttributes(int index) {
      return instance.getAttributes(index);
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder setAttributes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
      copyOnWrite();
      instance.setAttributes(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder setAttributes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute.Builder builderForValue) {
      copyOnWrite();
      instance.setAttributes(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder addAttributes(org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
      copyOnWrite();
      instance.addAttributes(value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder addAttributes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute value) {
      copyOnWrite();
      instance.addAttributes(index, value);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder addAttributes(
        org.firstinspires.ftc.teamcode.data.protocol.Attribute.Builder builderForValue) {
      copyOnWrite();
      instance.addAttributes(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder addAttributes(
        int index, org.firstinspires.ftc.teamcode.data.protocol.Attribute.Builder builderForValue) {
      copyOnWrite();
      instance.addAttributes(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder addAllAttributes(
        java.lang.Iterable<? extends org.firstinspires.ftc.teamcode.data.protocol.Attribute> values) {
      copyOnWrite();
      instance.addAllAttributes(values);
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder clearAttributes() {
      copyOnWrite();
      instance.clearAttributes();
      return this;
    }
    /**
     * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
     */
    public Builder removeAttributes(int index) {
      copyOnWrite();
      instance.removeAttributes(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.Event)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.Event();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "severity_",
            "attributes_",
            org.firstinspires.ftc.teamcode.data.protocol.Attribute.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\f" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.Event> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.Event.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.Event>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.Event)
  private static final org.firstinspires.ftc.teamcode.data.protocol.Event DEFAULT_INSTANCE;
  static {
    Event defaultInstance = new Event();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Event.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Event> PARSER;

  public static com.google.protobuf.Parser<Event> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

