// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Event)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @return The enum numeric value on the wire for severity.
   */
  int getSeverityValue();
  /**
   * <code>.ftc.robotdata.v2.Severity severity = 2;</code>
   * @return The severity.
   */
  org.firstinspires.ftc.teamcode.data.protocol.Severity getSeverity();

  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  java.util.List<org.firstinspires.ftc.teamcode.data.protocol.Attribute> 
      getAttributesList();
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  org.firstinspires.ftc.teamcode.data.protocol.Attribute getAttributes(int index);
  /**
   * <code>repeated .ftc.robotdata.v2.Attribute attributes = 3;</code>
   */
  int getAttributesCount();
}
