// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.Gap}
 */
public  final class Gap extends
    com.google.protobuf.GeneratedMessageLite<
        Gap, Gap.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.Gap)
    GapOrBuilder {
  private Gap() {
    reason_ = "";
  }
  public static final int FIRST_MISSING_SAMPLE_SEQUENCE_FIELD_NUMBER = 1;
  private long firstMissingSampleSequence_;
  /**
   * <code>uint64 first_missing_sample_sequence = 1;</code>
   * @return The firstMissingSampleSequence.
   */
  @java.lang.Override
  public long getFirstMissingSampleSequence() {
    return firstMissingSampleSequence_;
  }
  /**
   * <code>uint64 first_missing_sample_sequence = 1;</code>
   * @param value The firstMissingSampleSequence to set.
   */
  private void setFirstMissingSampleSequence(long value) {
    
    firstMissingSampleSequence_ = value;
  }
  /**
   * <code>uint64 first_missing_sample_sequence = 1;</code>
   */
  private void clearFirstMissingSampleSequence() {

    firstMissingSampleSequence_ = 0L;
  }

  public static final int LAST_MISSING_SAMPLE_SEQUENCE_FIELD_NUMBER = 2;
  private long lastMissingSampleSequence_;
  /**
   * <code>uint64 last_missing_sample_sequence = 2;</code>
   * @return The lastMissingSampleSequence.
   */
  @java.lang.Override
  public long getLastMissingSampleSequence() {
    return lastMissingSampleSequence_;
  }
  /**
   * <code>uint64 last_missing_sample_sequence = 2;</code>
   * @param value The lastMissingSampleSequence to set.
   */
  private void setLastMissingSampleSequence(long value) {
    
    lastMissingSampleSequence_ = value;
  }
  /**
   * <code>uint64 last_missing_sample_sequence = 2;</code>
   */
  private void clearLastMissingSampleSequence() {

    lastMissingSampleSequence_ = 0L;
  }

  public static final int REASON_FIELD_NUMBER = 3;
  private java.lang.String reason_;
  /**
   * <code>string reason = 3;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 3;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 3;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 3;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 3;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Gap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.Gap prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.Gap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.Gap, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.Gap)
      org.firstinspires.ftc.teamcode.data.protocol.GapOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.Gap.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint64 first_missing_sample_sequence = 1;</code>
     * @return The firstMissingSampleSequence.
     */
    @java.lang.Override
    public long getFirstMissingSampleSequence() {
      return instance.getFirstMissingSampleSequence();
    }
    /**
     * <code>uint64 first_missing_sample_sequence = 1;</code>
     * @param value The firstMissingSampleSequence to set.
     * @return This builder for chaining.
     */
    public Builder setFirstMissingSampleSequence(long value) {
      copyOnWrite();
      instance.setFirstMissingSampleSequence(value);
      return this;
    }
    /**
     * <code>uint64 first_missing_sample_sequence = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstMissingSampleSequence() {
      copyOnWrite();
      instance.clearFirstMissingSampleSequence();
      return this;
    }

    /**
     * <code>uint64 last_missing_sample_sequence = 2;</code>
     * @return The lastMissingSampleSequence.
     */
    @java.lang.Override
    public long getLastMissingSampleSequence() {
      return instance.getLastMissingSampleSequence();
    }
    /**
     * <code>uint64 last_missing_sample_sequence = 2;</code>
     * @param value The lastMissingSampleSequence to set.
     * @return This builder for chaining.
     */
    public Builder setLastMissingSampleSequence(long value) {
      copyOnWrite();
      instance.setLastMissingSampleSequence(value);
      return this;
    }
    /**
     * <code>uint64 last_missing_sample_sequence = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMissingSampleSequence() {
      copyOnWrite();
      instance.clearLastMissingSampleSequence();
      return this;
    }

    /**
     * <code>string reason = 3;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 3;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 3;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.Gap)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.Gap();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "firstMissingSampleSequence_",
            "lastMissingSampleSequence_",
            "reason_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0003\u0002\u0003" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.Gap> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.Gap.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.Gap>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.Gap)
  private static final org.firstinspires.ftc.teamcode.data.protocol.Gap DEFAULT_INSTANCE;
  static {
    Gap defaultInstance = new Gap();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Gap.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Gap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Gap> PARSER;

  public static com.google.protobuf.Parser<Gap> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

