// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Hello)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string robot_id = 1;</code>
   * @return The robotId.
   */
  java.lang.String getRobotId();
  /**
   * <code>string robot_id = 1;</code>
   * @return The bytes for robotId.
   */
  com.google.protobuf.ByteString
      getRobotIdBytes();

  /**
   * <code>string robot_name = 2;</code>
   * @return The robotName.
   */
  java.lang.String getRobotName();
  /**
   * <code>string robot_name = 2;</code>
   * @return The bytes for robotName.
   */
  com.google.protobuf.ByteString
      getRobotNameBytes();

  /**
   * <code>string op_mode_name = 3;</code>
   * @return The opModeName.
   */
  java.lang.String getOpModeName();
  /**
   * <code>string op_mode_name = 3;</code>
   * @return The bytes for opModeName.
   */
  com.google.protobuf.ByteString
      getOpModeNameBytes();

  /**
   * <code>uint64 started_at_robot_time_ns = 4;</code>
   * @return The startedAtRobotTimeNs.
   */
  long getStartedAtRobotTimeNs();

  /**
   * <code>uint32 queue_capacity = 5;</code>
   * @return The queueCapacity.
   */
  int getQueueCapacity();

  /**
   * <code>repeated string capabilities = 6;</code>
   * @return A list containing the capabilities.
   */
  java.util.List<java.lang.String>
      getCapabilitiesList();
  /**
   * <code>repeated string capabilities = 6;</code>
   * @return The count of capabilities.
   */
  int getCapabilitiesCount();
  /**
   * <code>repeated string capabilities = 6;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  java.lang.String getCapabilities(int index);
  /**
   * <code>repeated string capabilities = 6;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  com.google.protobuf.ByteString
      getCapabilitiesBytes(int index);
}
