// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface Pose2dOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Pose2d)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double heading_rad = 3;</code>
   * @return The headingRad.
   */
  double getHeadingRad();
}
