// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf type {@code ftc.robotdata.v2.Pose2d}
 */
public  final class Pose2d extends
    com.google.protobuf.GeneratedMessageLite<
        Pose2d, Pose2d.Builder> implements
    // @@protoc_insertion_point(message_implements:ftc.robotdata.v2.Pose2d)
    Pose2dOrBuilder {
  private Pose2d() {
  }
  public static final int X_FIELD_NUMBER = 1;
  private double x_;
  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public double getX() {
    return x_;
  }
  /**
   * <code>double x = 1;</code>
   * @param value The x to set.
   */
  private void setX(double value) {
    
    x_ = value;
  }
  /**
   * <code>double x = 1;</code>
   */
  private void clearX() {

    x_ = 0D;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private double y_;
  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  @java.lang.Override
  public double getY() {
    return y_;
  }
  /**
   * <code>double y = 2;</code>
   * @param value The y to set.
   */
  private void setY(double value) {
    
    y_ = value;
  }
  /**
   * <code>double y = 2;</code>
   */
  private void clearY() {

    y_ = 0D;
  }

  public static final int HEADING_RAD_FIELD_NUMBER = 3;
  private double headingRad_;
  /**
   * <code>double heading_rad = 3;</code>
   * @return The headingRad.
   */
  @java.lang.Override
  public double getHeadingRad() {
    return headingRad_;
  }
  /**
   * <code>double heading_rad = 3;</code>
   * @param value The headingRad to set.
   */
  private void setHeadingRad(double value) {
    
    headingRad_ = value;
  }
  /**
   * <code>double heading_rad = 3;</code>
   */
  private void clearHeadingRad() {

    headingRad_ = 0D;
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(org.firstinspires.ftc.teamcode.data.protocol.Pose2d prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code ftc.robotdata.v2.Pose2d}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        org.firstinspires.ftc.teamcode.data.protocol.Pose2d, Builder> implements
      // @@protoc_insertion_point(builder_implements:ftc.robotdata.v2.Pose2d)
      org.firstinspires.ftc.teamcode.data.protocol.Pose2dOrBuilder {
    // Construct using org.firstinspires.ftc.teamcode.data.protocol.Pose2d.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return instance.getX();
    }
    /**
     * <code>double x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(double value) {
      copyOnWrite();
      instance.setX(value);
      return this;
    }
    /**
     * <code>double x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      copyOnWrite();
      instance.clearX();
      return this;
    }

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return instance.getY();
    }
    /**
     * <code>double y = 2;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(double value) {
      copyOnWrite();
      instance.setY(value);
      return this;
    }
    /**
     * <code>double y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      copyOnWrite();
      instance.clearY();
      return this;
    }

    /**
     * <code>double heading_rad = 3;</code>
     * @return The headingRad.
     */
    @java.lang.Override
    public double getHeadingRad() {
      return instance.getHeadingRad();
    }
    /**
     * <code>double heading_rad = 3;</code>
     * @param value The headingRad to set.
     * @return This builder for chaining.
     */
    public Builder setHeadingRad(double value) {
      copyOnWrite();
      instance.setHeadingRad(value);
      return this;
    }
    /**
     * <code>double heading_rad = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeadingRad() {
      copyOnWrite();
      instance.clearHeadingRad();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ftc.robotdata.v2.Pose2d)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new org.firstinspires.ftc.teamcode.data.protocol.Pose2d();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "x_",
            "y_",
            "headingRad_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
              "\u0003\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<org.firstinspires.ftc.teamcode.data.protocol.Pose2d> parser = PARSER;
        if (parser == null) {
          synchronized (org.firstinspires.ftc.teamcode.data.protocol.Pose2d.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<org.firstinspires.ftc.teamcode.data.protocol.Pose2d>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:ftc.robotdata.v2.Pose2d)
  private static final org.firstinspires.ftc.teamcode.data.protocol.Pose2d DEFAULT_INSTANCE;
  static {
    Pose2d defaultInstance = new Pose2d();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Pose2d.class, defaultInstance);
  }

  public static org.firstinspires.ftc.teamcode.data.protocol.Pose2d getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Pose2d> PARSER;

  public static com.google.protobuf.Parser<Pose2d> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

