// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

/**
 * Protobuf enum {@code ftc.robotdata.v2.Severity}
 */
public enum Severity
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>SEVERITY_UNSPECIFIED = 0;</code>
   */
  SEVERITY_UNSPECIFIED(0),
  /**
   * <code>DEBUG = 1;</code>
   */
  DEBUG(1),
  /**
   * <code>INFO = 2;</code>
   */
  INFO(2),
  /**
   * <code>WARNING = 3;</code>
   */
  WARNING(3),
  /**
   * <code>EVENT_ERROR = 4;</code>
   */
  EVENT_ERROR(4),
  /**
   * <code>CRITICAL = 5;</code>
   */
  CRITICAL(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SEVERITY_UNSPECIFIED = 0;</code>
   */
  public static final int SEVERITY_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DEBUG = 1;</code>
   */
  public static final int DEBUG_VALUE = 1;
  /**
   * <code>INFO = 2;</code>
   */
  public static final int INFO_VALUE = 2;
  /**
   * <code>WARNING = 3;</code>
   */
  public static final int WARNING_VALUE = 3;
  /**
   * <code>EVENT_ERROR = 4;</code>
   */
  public static final int EVENT_ERROR_VALUE = 4;
  /**
   * <code>CRITICAL = 5;</code>
   */
  public static final int CRITICAL_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Severity valueOf(int value) {
    return forNumber(value);
  }

  public static Severity forNumber(int value) {
    switch (value) {
      case 0: return SEVERITY_UNSPECIFIED;
      case 1: return DEBUG;
      case 2: return INFO;
      case 3: return WARNING;
      case 4: return EVENT_ERROR;
      case 5: return CRITICAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Severity>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Severity> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Severity>() {
          @java.lang.Override
          public Severity findValueByNumber(int number) {
            return Severity.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return SeverityVerifier.INSTANCE;
  }

  private static final class SeverityVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new SeverityVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return Severity.forNumber(number) != null;
          }
        };

  private final int value;

  private Severity(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ftc.robotdata.v2.Severity)
}

