// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot_data.proto

// Protobuf Java Version: 3.25.5
package org.firstinspires.ftc.teamcode.data.protocol;

public interface Vector3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftc.robotdata.v2.Vector3)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3;</code>
   * @return The z.
   */
  double getZ();
}
